/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PointArray } from './point-array';
// May contain unused imports in some cases
// @ts-ignore
import type { RectangleCoordinates } from './rectangle-coordinates';

/**
 * 
 * @export
 * @interface AreaArray
 */
export interface AreaArray {
    /**
     * Number of elements in List and Points
     * @type {number}
     * @memberof AreaArray
     */
    'Count': number;
    /**
     * 
     * @type {Array<RectangleCoordinates>}
     * @memberof AreaArray
     */
    'List': Array<RectangleCoordinates>;
    /**
     * 
     * @type {Array<PointArray>}
     * @memberof AreaArray
     */
    'Points': Array<PointArray>;
}

