/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PointsContainer } from './points-container';
// May contain unused imports in some cases
// @ts-ignore
import type { RectangleCoordinates } from './rectangle-coordinates';

/**
 * Checked fragment coordinates
 * @export
 * @interface AreaContainer
 */
export interface AreaContainer {
    /**
     * 
     * @type {number}
     * @memberof AreaContainer
     */
    'Count': number;
    /**
     * 
     * @type {Array<RectangleCoordinates>}
     * @memberof AreaContainer
     */
    'List': Array<RectangleCoordinates>;
    /**
     * 
     * @type {Array<PointsContainer>}
     * @memberof AreaContainer
     */
    'Points': Array<PointsContainer>;
}

