/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthenticityCheckResult } from './authenticity-check-result';

/**
 * 
 * @export
 * @interface AuthenticityCheckList
 */
export interface AuthenticityCheckList {
    /**
     * Count of items in List
     * @type {number}
     * @memberof AuthenticityCheckList
     */
    'Count': number;
    /**
     * Authenticity Check
     * @type {Array<AuthenticityCheckResult>}
     * @memberof AuthenticityCheckList
     */
    'List': Array<AuthenticityCheckResult>;
}

