/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthenticityCheckList } from './authenticity-check-list';

/**
 * 
 * @export
 * @interface AuthenticityCheckListItem
 */
export interface AuthenticityCheckListItem {
    /**
     * 
     * @type {AuthenticityCheckList}
     * @memberof AuthenticityCheckListItem
     */
    'AuthenticityCheckList': AuthenticityCheckList;
}

