/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 8.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Enumeration contains the types of barcodes that can be processed
 * @export
 * @enum {number}
 */

export enum BarcodeType {
    /**
    * Unknown
    */
    UNKNOWN = 0,
    /**
    * Code 128
    */
    CODE128 = 1,
    /**
    * Code 39
    */
    CODE39 = 2,
    /**
    * EAN-8
    */
    EAN8 = 3,
    /**
    * ITF
    */
    ITF = 4,
    /**
    * PDF417
    */
    PDF417 = 5,
    /**
    * STF
    */
    STF = 6,
    /**
    * MTF
    */
    MTF = 7,
    /**
    * IATA
    */
    IATA = 8,
    /**
    * Codabar
    */
    CODABAR = 9,
    /**
    * UPC-A
    */
    UPCA = 10,
    /**
    * Code 93
    */
    CODE93 = 11,
    /**
    * UPC-E
    */
    UPCE = 12,
    /**
    * EAN-13
    */
    EAN13 = 13,
    /**
    * QR code
    */
    QRCODE = 14,
    /**
    * Aztec code
    */
    AZTEC = 15,
    /**
    * Datamatrix
    */
    DATAMATRIX = 16,
    /**
    * All 1D barcodes
    */
    ALL_1D = 17,
    /**
    * Code 11
    */
    CODE11 = 18,
    /**
    * JAB code
    */
    JABCODE = 19
}



