/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BcPDF417INFO
 */
export interface BcPDF417INFO {
    /**
     * 
     * @type {number}
     * @memberof BcPDF417INFO
     */
    'Angle': number;
    /**
     * 
     * @type {number}
     * @memberof BcPDF417INFO
     */
    'bcColumn': number;
    /**
     * 
     * @type {number}
     * @memberof BcPDF417INFO
     */
    'bcErrorLevel': number;
    /**
     * 
     * @type {number}
     * @memberof BcPDF417INFO
     */
    'bcRow': number;
    /**
     * 
     * @type {number}
     * @memberof BcPDF417INFO
     */
    'minX': number;
    /**
     * 
     * @type {number}
     * @memberof BcPDF417INFO
     */
    'minY': number;
}

