/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BcROIDETECT
 */
export interface BcROIDETECT {
    /**
     * 
     * @type {number}
     * @memberof BcROIDETECT
     */
    'bottom': number;
    /**
     * 
     * @type {number}
     * @memberof BcROIDETECT
     */
    'left': number;
    /**
     * 
     * @type {number}
     * @memberof BcROIDETECT
     */
    'right': number;
    /**
     * 
     * @type {number}
     * @memberof BcROIDETECT
     */
    'top': number;
}

