/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @interface BsiTr03135
 */
export interface BsiTr03135 {
    /**
     * When enabled, returns processing results in accordance with the BSI TR-03135 standard in addition to the existing processing results.
     * @type {boolean}
     * @memberof BsiTr03135
     */
    'generateResult'?: boolean;
}

