/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @interface BSIV2Item
 */
export interface BSIV2Item {
    /**
     * 
     * @type {string}
     * @memberof BSIV2Item
     */
    'XML_buffer': string;
}

