/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ByteArrayItem
 */
export interface ByteArrayItem {
    /**
     * Byte array in base64
     * @type {string}
     * @memberof ByteArrayItem
     */
    'ByteArray': string;
}

