/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DocumentTypesCandidatesList } from './document-types-candidates-list';

/**
 * 
 * @export
 * @interface CandidatesListItem
 */
export interface CandidatesListItem {
    /**
     * 
     * @type {DocumentTypesCandidatesList}
     * @memberof CandidatesListItem
     */
    'CandidatesList'?: DocumentTypesCandidatesList;
}

