/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FDSIDList } from './fdsidlist';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidLocation } from './rfid-location';

/**
 * Contains information about one document type candidate
 * @export
 * @interface ChosenDocumentType
 */
export interface ChosenDocumentType {
    /**
     * Document name
     * @type {string}
     * @memberof ChosenDocumentType
     */
    'DocumentName'?: string;
    /**
     * Unique document type template identifier (Regula\'s internal numeric code)
     * @type {number}
     * @memberof ChosenDocumentType
     */
    'ID': number;
    /**
     * A measure of the likelihood of correct recognition in the analysis of this type of document
     * @type {number}
     * @memberof ChosenDocumentType
     */
    'P': number;
    /**
     * Indicates if the document of the given type is rotated by 180 degrees
     * @type {number}
     * @memberof ChosenDocumentType
     */
    'Rotated180': number;
    /**
     * 
     * @type {RfidLocation}
     * @memberof ChosenDocumentType
     */
    'RFID_Presence': RfidLocation;
    /**
     * 
     * @type {FDSIDList}
     * @memberof ChosenDocumentType
     */
    'FDSIDList'?: FDSIDList;
    /**
     * Combination of lighting scheme identifiers (Light enum) required to conduct OCR for this type of document
     * @type {number}
     * @memberof ChosenDocumentType
     */
    'NecessaryLights': number;
    /**
     * Set of authentication options provided for this type of document (combination of Authenticity enum)
     * @type {number}
     * @memberof ChosenDocumentType
     */
    'CheckAuthenticity': number;
    /**
     * The required exposure value of the camera when receiving images of a document of this type for a UV lighting scheme
     * @type {number}
     * @memberof ChosenDocumentType
     */
    'UVExp': number;
    /**
     * Combination of lighting scheme identifiers (combination of Light enum) needed to perform all authenticity checks specified in CheckAuthenticity
     * @type {number}
     * @memberof ChosenDocumentType
     */
    'AuthenticityNecessaryLights': number;
    /**
     * Camera exposure value necessary when obtaining document images of the given type for AXIAL lighting scheme
     * @type {number}
     * @memberof ChosenDocumentType
     */
    'OVIExp': number;
    /**
     * 
     * @type {number}
     * @memberof ChosenDocumentType
     */
    'RotationAngle'?: number;
}



