/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContainerListListInner } from './container-list-list-inner';

/**
 * List with various objects, containing processing results
 * @export
 * @interface ContainerList
 */
export interface ContainerList {
    /**
     * Length of list (Count for items)
     * @type {number}
     * @memberof ContainerList
     */
    'Count'?: number;
    /**
     * 
     * @type {Array<ContainerListListInner>}
     * @memberof ContainerList
     */
    'List': Array<ContainerListListInner>;
}

