/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthenticityCheckList } from './authenticity-check-list';
// May contain unused imports in some cases
// @ts-ignore
import type { AuthenticityResult } from './authenticity-result';
// May contain unused imports in some cases
// @ts-ignore
import type { ByteArrayResult } from './byte-array-result';
// May contain unused imports in some cases
// @ts-ignore
import type { ChosenDocumentTypeResult } from './chosen-document-type-result';
// May contain unused imports in some cases
// @ts-ignore
import type { DocBarCodeInfo } from './doc-bar-code-info';
// May contain unused imports in some cases
// @ts-ignore
import type { DocBarCodeInfoFieldsList } from './doc-bar-code-info-fields-list';
// May contain unused imports in some cases
// @ts-ignore
import type { DocumentBinaryInfoResult } from './document-binary-info-result';
// May contain unused imports in some cases
// @ts-ignore
import type { DocumentImageResult } from './document-image-result';
// May contain unused imports in some cases
// @ts-ignore
import type { DocumentPosition } from './document-position';
// May contain unused imports in some cases
// @ts-ignore
import type { DocumentPositionResult } from './document-position-result';
// May contain unused imports in some cases
// @ts-ignore
import type { DocumentTypesCandidatesList } from './document-types-candidates-list';
// May contain unused imports in some cases
// @ts-ignore
import type { DocumentTypesCandidatesResult } from './document-types-candidates-result';
// May contain unused imports in some cases
// @ts-ignore
import type { EncryptedRCLResult } from './encrypted-rclresult';
// May contain unused imports in some cases
// @ts-ignore
import type { FaceDetection } from './face-detection';
// May contain unused imports in some cases
// @ts-ignore
import type { FaceDetectionResult } from './face-detection-result';
// May contain unused imports in some cases
// @ts-ignore
import type { GraphicFieldsList } from './graphic-fields-list';
// May contain unused imports in some cases
// @ts-ignore
import type { GraphicsResult } from './graphics-result';
// May contain unused imports in some cases
// @ts-ignore
import type { ImageData } from './image-data';
// May contain unused imports in some cases
// @ts-ignore
import type { ImageQualityCheckList } from './image-quality-check-list';
// May contain unused imports in some cases
// @ts-ignore
import type { ImageQualityResult } from './image-quality-result';
// May contain unused imports in some cases
// @ts-ignore
import type { Images } from './images';
// May contain unused imports in some cases
// @ts-ignore
import type { ImagesResult } from './images-result';
// May contain unused imports in some cases
// @ts-ignore
import type { LexicalAnalysisResult } from './lexical-analysis-result';
// May contain unused imports in some cases
// @ts-ignore
import type { LicenseResult } from './license-result';
// May contain unused imports in some cases
// @ts-ignore
import type { ListVerifiedFields } from './list-verified-fields';
// May contain unused imports in some cases
// @ts-ignore
import type { MRZDetectorResult } from './mrzdetector-result';
// May contain unused imports in some cases
// @ts-ignore
import type { MRZPositionResult } from './mrzposition-result';
// May contain unused imports in some cases
// @ts-ignore
import type { MRZTestQuality } from './mrztest-quality';
// May contain unused imports in some cases
// @ts-ignore
import type { MRZTestQualityResult } from './mrztest-quality-result';
// May contain unused imports in some cases
// @ts-ignore
import type { OneCandidate } from './one-candidate';
// May contain unused imports in some cases
// @ts-ignore
import type { RFIDDocVisualExtendedInfo } from './rfiddoc-visual-extended-info';
// May contain unused imports in some cases
// @ts-ignore
import type { RFIDGraphicsInfoResult } from './rfidgraphics-info-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RFIDTextDataResult } from './rfidtext-data-result';
// May contain unused imports in some cases
// @ts-ignore
import type { Result } from './result';
// May contain unused imports in some cases
// @ts-ignore
import type { ResultMRZDetector } from './result-mrzdetector';
// May contain unused imports in some cases
// @ts-ignore
import type { Status } from './status';
// May contain unused imports in some cases
// @ts-ignore
import type { StatusResult } from './status-result';
// May contain unused imports in some cases
// @ts-ignore
import type { TDocBinaryInfo } from './tdoc-binary-info';
// May contain unused imports in some cases
// @ts-ignore
import type { TOriginalRFIDGraphicsInfo } from './toriginal-rfidgraphics-info';
// May contain unused imports in some cases
// @ts-ignore
import type { Text } from './text';
// May contain unused imports in some cases
// @ts-ignore
import type { TextDataResult } from './text-data-result';
// May contain unused imports in some cases
// @ts-ignore
import type { TextResult } from './text-result';

/**
 * @type ContainerListListInner
 * @export
 */
export type ContainerListListInner = AuthenticityResult | ByteArrayResult | ChosenDocumentTypeResult | DocBarCodeInfo | DocumentBinaryInfoResult | DocumentImageResult | DocumentPositionResult | DocumentTypesCandidatesResult | EncryptedRCLResult | FaceDetectionResult | GraphicsResult | ImageQualityResult | ImagesResult | LexicalAnalysisResult | LicenseResult | MRZDetectorResult | MRZPositionResult | MRZTestQualityResult | RFIDGraphicsInfoResult | RFIDTextDataResult | StatusResult | TextDataResult | TextResult;


