/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * Enumeration contains identifiers determining the criticality of the security element
 * @export
 * @enum {number}
 */

export enum Critical {
    /**
    * Security element may be absent in a valid document
    */
    NOT_CRITICAL = 0,
    /**
    * Security element must be present in a valid document
    */
    CRITICAL = 1
}



