/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DocumentType } from './document-type';

/**
 * 
 * @export
 * @interface DatabaseDocument
 */
export interface DatabaseDocument {
    /**
     * Whether the document has a barcode.
     * @type {boolean}
     * @memberof DatabaseDocument
     */
    'barcode_fields': boolean;
    /**
     * Country name.
     * @type {string}
     * @memberof DatabaseDocument
     */
    'country': string;
    /**
     * Date when the document description was created in the database.
     * @type {string}
     * @memberof DatabaseDocument
     */
    'createad': string;
    /**
     * 
     * @type {DocumentType}
     * @memberof DatabaseDocument
     */
    'doc_type': DocumentType;
    /**
     * Document name.
     * @type {string}
     * @memberof DatabaseDocument
     */
    'document': string;
    /**
     * The presence of graphic fields in the document.
     * @type {boolean}
     * @memberof DatabaseDocument
     */
    'graphic_fields': boolean;
    /**
     * Document code.
     * @type {number}
     * @memberof DatabaseDocument
     */
    'id': number;
    /**
     * The document has an MRZ.
     * @type {boolean}
     * @memberof DatabaseDocument
     */
    'mrz': boolean;
    /**
     * Country region.
     * @type {string}
     * @memberof DatabaseDocument
     */
    'region'?: string;
    /**
     * The document has an RFID chip.
     * @type {boolean}
     * @memberof DatabaseDocument
     */
    'rfid_chip': boolean;
    /**
     * The presence of text fields in the document.
     * @type {boolean}
     * @memberof DatabaseDocument
     */
    'text_fields': boolean;
    /**
     * Date when the document description was updated in the database.
     * @type {string}
     * @memberof DatabaseDocument
     */
    'updated': string;
    /**
     * The year when the document was issued.
     * @type {string}
     * @memberof DatabaseDocument
     */
    'year'?: string;
    /**
     * Guardian country.
     * @type {string}
     * @memberof DatabaseDocument
     */
    'sovereignty'?: string;
    /**
     * Whether the document is no longer in circulation.
     * @type {boolean}
     * @memberof DatabaseDocument
     */
    'deprecated'?: boolean;
    /**
     * ICAO country code.
     * @type {string}
     * @memberof DatabaseDocument
     */
    'icao_code'?: string;
    /**
     * Document codes.
     * @type {string}
     * @memberof DatabaseDocument
     */
    'doc_codes'?: string;
}



