/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BarCodeModuleType } from './bar-code-module-type';

/**
 * 
 * @export
 * @interface DataModule
 */
export interface DataModule {
    /**
     * 
     * @type {string}
     * @memberof DataModule
     */
    'mData': string;
    /**
     * 
     * @type {number}
     * @memberof DataModule
     */
    'mLength': number;
    /**
     * 
     * @type {number}
     * @memberof DataModule
     */
    'mReserved1'?: number;
    /**
     * 
     * @type {number}
     * @memberof DataModule
     */
    'mReserver2'?: number;
    /**
     * 
     * @type {BarCodeModuleType}
     * @memberof DataModule
     */
    'mType': BarCodeModuleType;
}



