/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CheckResult } from './check-result';

/**
 * Details on performed optical checks
 * @export
 * @interface DetailsOptical
 */
export interface DetailsOptical {
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsOptical
     */
    'overallStatus': CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsOptical
     */
    'docType': CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsOptical
     */
    'expiry': CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsOptical
     */
    'imageQA': CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsOptical
     */
    'mrz': CheckResult;
    /**
     * Number of processed pages in the document
     * @type {number}
     * @memberof DetailsOptical
     */
    'pagesCount': number;
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsOptical
     */
    'security': CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsOptical
     */
    'text': CheckResult;
    /**
     * 
     * @type {number}
     * @memberof DetailsOptical
     */
    'vds'?: number;
}



