/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CheckResult } from './check-result';

/**
 * 
 * @export
 * @interface DetailsAge
 */
export interface DetailsAge {
    /**
     * 
     * @type {number}
     * @memberof DetailsAge
     */
    'threshold': number;
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsAge
     */
    'overThreshold': CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsAge
     */
    'over18': CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsAge
     */
    'over21': CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsAge
     */
    'over25': CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsAge
     */
    'over65': CheckResult;
}



