/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CheckResult } from './check-result';

/**
 * Details on performed optical checks
 * @export
 * @interface DetailsOptical
 */
export interface DetailsOptical {
    /**
     * Overall optical checks combined status
     * @type {CheckResult}
     * @memberof DetailsOptical
     */
    'overallStatus': CheckResult;
    /**
     * Status of document type recognition
     * @type {CheckResult}
     * @memberof DetailsOptical
     */
    'docType': CheckResult;
    /**
     * Status of document expiration
     * @type {CheckResult}
     * @memberof DetailsOptical
     */
    'expiry': CheckResult;
    /**
     * Status of document image quality check
     * @type {CheckResult}
     * @memberof DetailsOptical
     */
    'imageQA': CheckResult;
    /**
     * Status of document MRZ
     * @type {CheckResult}
     * @memberof DetailsOptical
     */
    'mrz': CheckResult;
    /**
     * Number of processed pages in the document
     * @type {number}
     * @memberof DetailsOptical
     */
    'pagesCount': number;
    /**
     * Authenticity verification status
     * @type {CheckResult}
     * @memberof DetailsOptical
     */
    'security': CheckResult;
    /**
     * Status of text fields analysis
     * @type {CheckResult}
     * @memberof DetailsOptical
     */
    'text': CheckResult;
    /**
     * 
     * @type {number}
     * @memberof DetailsOptical
     */
    'vds'?: number;
}



