/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 8.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DeviceInfoDocumentsDatabase } from './device-info-documents-database';

/**
 * 
 * @export
 * @interface DeviceInfo
 */
export interface DeviceInfo {
    /**
     * Application name.
     * @type {string}
     * @memberof DeviceInfo
     */
    'app-name'?: string;
    /**
     * Product version.
     * @type {string}
     * @memberof DeviceInfo
     */
    'version'?: string;
    /**
     * Unique license identifier.
     * @type {string}
     * @memberof DeviceInfo
     */
    'license-id'?: string;
    /**
     * License serial number.
     * @type {string}
     * @memberof DeviceInfo
     */
    'license-serial'?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceInfo
     */
    'license-type'?: string;
    /**
     * License validity date.
     * @type {string}
     * @memberof DeviceInfo
     */
    'valid-until'?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceInfo
     */
    'server-time'?: string;
    /**
     * List of supported scenarios.
     * @type {Array<string>}
     * @memberof DeviceInfo
     */
    'supported-scenarios'?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof DeviceInfo
     */
    'metadata'?: { [key: string]: any; };
    /**
     * 
     * @type {DeviceInfoDocumentsDatabase}
     * @memberof DeviceInfo
     */
    'documents-database'?: DeviceInfoDocumentsDatabase;
}

