/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.  # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeviceInfo
 */
export interface DeviceInfo {
    /**
     * 
     * @type {string}
     * @memberof DeviceInfo
     */
    app?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceInfo
     */
    licenseId?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceInfo
     */
    licenseType?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceInfo
     */
    licenseSerial?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceInfo
     */
    licenseValidUntil?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DeviceInfo
     */
    scenarios?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DeviceInfo
     */
    version?: string;
}
