/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * Database information.
 * @export
 * @interface DeviceInfoDocumentsDatabase
 */
export interface DeviceInfoDocumentsDatabase {
    /**
     * Database identifier.
     * @type {string}
     * @memberof DeviceInfoDocumentsDatabase
     */
    'id': string | null;
    /**
     * Database version.
     * @type {string}
     * @memberof DeviceInfoDocumentsDatabase
     */
    'version': string | null;
    /**
     * Date of database creation.
     * @type {string}
     * @memberof DeviceInfoDocumentsDatabase
     */
    'export-date': string | null;
    /**
     * Description of the database contents, such as the list of supported countries and documents.
     * @type {string}
     * @memberof DeviceInfoDocumentsDatabase
     */
    'description': string | null;
}

