/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DocVisualExtendedInfo } from './doc-visual-extended-info';

/**
 * 
 * @export
 * @interface DocVisualExtendedInfoItem
 */
export interface DocVisualExtendedInfoItem {
    /**
     * 
     * @type {DocVisualExtendedInfo}
     * @memberof DocVisualExtendedInfoItem
     */
    'DocVisualExtendedInfo': DocVisualExtendedInfo;
}

