/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DocBarCodeInfoFieldsList } from './doc-bar-code-info-fields-list';
// May contain unused imports in some cases
// @ts-ignore
import type { DocBarCodeInfoItem } from './doc-bar-code-info-item';
// May contain unused imports in some cases
// @ts-ignore
import type { Result } from './result';
// May contain unused imports in some cases
// @ts-ignore
import type { ResultItem } from './result-item';

/**
 * @type DocBarCodeInfo
 * Raw data from BarCodes
 * @export
 */
export type DocBarCodeInfo = DocBarCodeInfoItem & ResultItem;


