/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { StringRecognitionResult } from './string-recognition-result';
import type { TextFieldType } from './text-field-type';

/**
 * 
 * @export
 * @interface DocVisualExtendedField
 */
export interface DocVisualExtendedField {
    /**
     * 
     * @type {any}
     * @memberof DocVisualExtendedField
     */
    FieldType: any | null;
    /**
     * 
     * @type {TextFieldType}
     * @memberof DocVisualExtendedField
     */
    wFieldType: TextFieldType;
    /**
     * Field symbolic name (null-terminated string)
     * @type {string}
     * @memberof DocVisualExtendedField
     */
    FieldName: string;
    /**
     * Number of StringsResult array elements
     * @type {number}
     * @memberof DocVisualExtendedField
     */
    StringsCount: number;
    /**
     * Array of recognizing probabilities for a each line of text field. Only for Result.VISUAL_TEXT and Result.MRZ_TEXT results.
     * @type {Array<StringRecognitionResult>}
     * @memberof DocVisualExtendedField
     */
    StringsResult: Array<StringRecognitionResult>;
    /**
     * Buf_Text text string length
     * @type {number}
     * @memberof DocVisualExtendedField
     */
    Buf_Length: number;
    /**
     * Text field data in UTF8 format. Results of reading different lines of a multi-line field are separated by \'^\'
     * @type {string}
     * @memberof DocVisualExtendedField
     */
    Buf_Text: string;
    /**
     * 
     * @type {any}
     * @memberof DocVisualExtendedField
     */
    FieldMask?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocVisualExtendedField
     */
    Validity?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocVisualExtendedField
     */
    InComparison?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocVisualExtendedField
     */
    Reserved2?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DocVisualExtendedField
     */
    Reserved3?: any | null;
}
