/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GraphicFieldsList } from './graphic-fields-list';

/**
 * 
 * @export
 * @interface DocGraphicsInfoItem
 */
export interface DocGraphicsInfoItem {
    /**
     * 
     * @type {GraphicFieldsList}
     * @memberof DocGraphicsInfoItem
     */
    'DocGraphicsInfo': GraphicFieldsList;
}

