/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DocBarCodeInfoFieldsList } from './doc-bar-code-info-fields-list';

/**
 * 
 * @export
 * @interface DocBarCodeInfoItem
 */
export interface DocBarCodeInfoItem {
    /**
     * 
     * @type {DocBarCodeInfoFieldsList}
     * @memberof DocBarCodeInfoItem
     */
    'DocBarCodeInfo': DocBarCodeInfoFieldsList;
}

