/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RectangleCoordinates } from './rectangle-coordinates';
// May contain unused imports in some cases
// @ts-ignore
import type { StringRecognitionResult } from './string-recognition-result';
// May contain unused imports in some cases
// @ts-ignore
import type { TextFieldType } from './text-field-type';

/**
 * Structure and serves for storing information from one text data field. Variant with field logical type and field rectangular area coordinates on the image.
 * @export
 * @interface DocVisualExtendedFieldRect
 */
export interface DocVisualExtendedFieldRect {
    /**
     * 
     * @type {RectangleCoordinates}
     * @memberof DocVisualExtendedFieldRect
     */
    'FieldRect'?: RectangleCoordinates;
    /**
     * 
     * @type {any}
     * @memberof DocVisualExtendedFieldRect
     */
    'FieldType': any;
    /**
     * 
     * @type {TextFieldType}
     * @memberof DocVisualExtendedFieldRect
     */
    'wFieldType': TextFieldType;
    /**
     * Field symbolic name (null-terminated string)
     * @type {string}
     * @memberof DocVisualExtendedFieldRect
     */
    'FieldName': string;
    /**
     * Number of StringsResult array elements
     * @type {number}
     * @memberof DocVisualExtendedFieldRect
     */
    'StringsCount': number;
    /**
     * Array of recognizing probabilities for a each line of text field. Only for Result.VISUAL_TEXT and Result.MRZ_TEXT results.
     * @type {Array<StringRecognitionResult>}
     * @memberof DocVisualExtendedFieldRect
     */
    'StringsResult': Array<StringRecognitionResult>;
    /**
     * Buf_Text text string length
     * @type {number}
     * @memberof DocVisualExtendedFieldRect
     */
    'Buf_Length': number;
    /**
     * Text field data in UTF8 format. Results of reading different lines of a multi-line field are separated by \'^\'
     * @type {string}
     * @memberof DocVisualExtendedFieldRect
     */
    'Buf_Text': string;
    /**
     * 
     * @type {any}
     * @memberof DocVisualExtendedFieldRect
     */
    'FieldMask'?: any;
    /**
     * 
     * @type {any}
     * @memberof DocVisualExtendedFieldRect
     */
    'Validity'?: any;
    /**
     * 
     * @type {any}
     * @memberof DocVisualExtendedFieldRect
     */
    'InComparison'?: any;
    /**
     * 
     * @type {any}
     * @memberof DocVisualExtendedFieldRect
     */
    'Reserved2'?: any;
    /**
     * 
     * @type {any}
     * @memberof DocVisualExtendedFieldRect
     */
    'Reserved3'?: any;
}



