/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RectangleCoordinates } from './rectangle-coordinates';

/**
 * 
 * @export
 * @interface DocVisualExtendedFieldItem
 */
export interface DocVisualExtendedFieldItem {
    /**
     * Coordinates of the text field in the normalized image of the document. Only for Result.VISUAL_TEXT and Result.MRZ_TEXT results.
     * @type {RectangleCoordinates}
     * @memberof DocVisualExtendedFieldItem
     */
    'FieldRect': RectangleCoordinates;
}

