/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TrfFtBytes } from './trf-ft-bytes';

/**
 * 
 * @export
 * @interface DocFeature
 */
export interface DocFeature {
    /**
     * 
     * @type {number}
     * @memberof DocFeature
     */
    'Type': number;
    /**
     * 
     * @type {TrfFtBytes}
     * @memberof DocFeature
     */
    'Data': TrfFtBytes;
}

