/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PArrayField } from './parray-field';

/**
 * 
 * @export
 * @interface DocBarCodeInfoFieldsList
 */
export interface DocBarCodeInfoFieldsList {
    /**
     * Count of array fields
     * @type {number}
     * @memberof DocBarCodeInfoFieldsList
     */
    'nFields': number;
    /**
     * Data from barcode
     * @type {Array<PArrayField>}
     * @memberof DocBarCodeInfoFieldsList
     */
    'pArrayFields': Array<PArrayField>;
}

