/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DocVisualExtendedField } from './doc-visual-extended-field';

/**
 * Container for extracted text fields. Fields are identified by type and language
 * @export
 * @interface DocVisualExtendedInfo
 */
export interface DocVisualExtendedInfo {
    /**
     * Number of pArrayFields array elements
     * @type {number}
     * @memberof DocVisualExtendedInfo
     */
    'nFields': number;
    /**
     * 
     * @type {Array<DocVisualExtendedField>}
     * @memberof DocVisualExtendedInfo
     */
    'pArrayFields': Array<DocVisualExtendedField>;
}

