/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RectangleCoordinates } from './rectangle-coordinates';

/**
 * 
 * @export
 * @interface DocVisualExtendedFieldItem
 */
export interface DocVisualExtendedFieldItem {
    /**
     * 
     * @type {RectangleCoordinates}
     * @memberof DocVisualExtendedFieldItem
     */
    'FieldRect': RectangleCoordinates;
}

