/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DocVisualExtendedFieldItem } from './doc-visual-extended-field-item';
// May contain unused imports in some cases
// @ts-ignore
import type { LCID } from './lcid';
// May contain unused imports in some cases
// @ts-ignore
import type { RectangleCoordinates } from './rectangle-coordinates';
// May contain unused imports in some cases
// @ts-ignore
import type { StringRecognitionResult } from './string-recognition-result';
// May contain unused imports in some cases
// @ts-ignore
import type { TextFieldType } from './text-field-type';
// May contain unused imports in some cases
// @ts-ignore
import type { VisualExtendedFieldItem } from './visual-extended-field-item';

/**
 * @type DocVisualExtendedField
 * @export
 */
export type DocVisualExtendedField = DocVisualExtendedFieldItem & VisualExtendedFieldItem;


