/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DocumentPosition } from './document-position';

/**
 * 
 * @export
 * @interface DocumentPositionItem
 */
export interface DocumentPositionItem {
    /**
     * 
     * @type {DocumentPosition}
     * @memberof DocumentPositionItem
     */
    'DocumentPosition': DocumentPosition;
}

