/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DocumentTypeRecognitionResult } from './document-type-recognition-result';
// May contain unused imports in some cases
// @ts-ignore
import type { OneCandidate } from './one-candidate';

/**
 * 
 * @export
 * @interface DocumentTypesCandidatesList
 */
export interface DocumentTypesCandidatesList {
    /**
     * 
     * @type {DocumentTypeRecognitionResult}
     * @memberof DocumentTypesCandidatesList
     */
    'RecResult'?: DocumentTypeRecognitionResult;
    /**
     * 
     * @type {Array<OneCandidate>}
     * @memberof DocumentTypesCandidatesList
     */
    'Candidates'?: Array<OneCandidate>;
}



