/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Document database information
 * @export
 * @interface DocumentsDatabase
 */
export interface DocumentsDatabase {
    /**
     * Document database description
     * @type {string}
     * @memberof DocumentsDatabase
     */
    'Description'?: string;
    /**
     * Date the document database was created
     * @type {string}
     * @memberof DocumentsDatabase
     */
    'ExportDate'?: string;
    /**
     * Document database identifier
     * @type {string}
     * @memberof DocumentsDatabase
     */
    'ID'?: string;
    /**
     * Document database version
     * @type {string}
     * @memberof DocumentsDatabase
     */
    'Version'?: string;
}

