/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DocumentImage
 */
export interface DocumentImage {
    /**
     * Base64 encoded image
     * @type {string}
     * @memberof DocumentImage
     */
    'image'?: string;
    /**
     * Image format
     * @type {string}
     * @memberof DocumentImage
     */
    'format'?: string;
}

