/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EncryptedRCLResult
 */
export interface EncryptedRCLResult {
    /**
     * Base64 encoded data
     * @type {string}
     * @memberof EncryptedRCLResult
     */
    'EncryptedRCL': string;
    /**
     * 
     * @type {number}
     * @memberof EncryptedRCLResult
     */
    'buf_length'?: number;
    /**
     * 
     * @type {number}
     * @memberof EncryptedRCLResult
     */
    'light'?: number;
    /**
     * 
     * @type {number}
     * @memberof EncryptedRCLResult
     */
    'list_idx'?: number;
    /**
     * 
     * @type {number}
     * @memberof EncryptedRCLResult
     */
    'page_idx'?: number;
    /**
     * Same as Result type, but used for safe parsing of not-described values. See Result type.
     * @type {number}
     * @memberof EncryptedRCLResult
     */
    'result_type': number;
}

