/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EncryptedRCLItem
 */
export interface EncryptedRCLItem {
    /**
     * Base64 encoded data
     * @type {string}
     * @memberof EncryptedRCLItem
     */
    'EncryptedRCL': string;
}

