/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EncryptedRCLItem } from './encrypted-rclitem';
// May contain unused imports in some cases
// @ts-ignore
import type { Result } from './result';
// May contain unused imports in some cases
// @ts-ignore
import type { ResultItem } from './result-item';

/**
 * @type EncryptedRCLResult
 * Contains encrypted result container list
 * @export
 */
export type EncryptedRCLResult = EncryptedRCLItem & ResultItem;


