/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @interface ErrorCoordinates
 */
export interface ErrorCoordinates {
    /**
     * 
     * @type {number}
     * @memberof ErrorCoordinates
     */
    'Left'?: number;
    /**
     * 
     * @type {number}
     * @memberof ErrorCoordinates
     */
    'Top'?: number;
    /**
     * 
     * @type {number}
     * @memberof ErrorCoordinates
     */
    'Right'?: number;
    /**
     * 
     * @type {number}
     * @memberof ErrorCoordinates
     */
    'Bottom'?: number;
}

