/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Light } from './light';
// May contain unused imports in some cases
// @ts-ignore
import type { Point } from './point';
// May contain unused imports in some cases
// @ts-ignore
import type { RectangleCoordinates } from './rectangle-coordinates';

/**
 * 
 * @export
 * @interface FaceItem
 */
export interface FaceItem {
    /**
     * 
     * @type {number}
     * @memberof FaceItem
     */
    'CoincidenceToPhotoArea': number;
    /**
     * 
     * @type {RectangleCoordinates}
     * @memberof FaceItem
     */
    'FaceRect': RectangleCoordinates;
    /**
     * 
     * @type {RectangleCoordinates}
     * @memberof FaceItem
     */
    'FieldRect': RectangleCoordinates;
    /**
     * 
     * @type {number}
     * @memberof FaceItem
     */
    'GraphFieldNumber': number;
    /**
     * 
     * @type {Array<Point>}
     * @memberof FaceItem
     */
    'Landmarks': Array<Point>;
    /**
     * 
     * @type {Light}
     * @memberof FaceItem
     */
    'LightType': Light;
    /**
     * 
     * @type {number}
     * @memberof FaceItem
     */
    'Orientation': number;
    /**
     * 
     * @type {number}
     * @memberof FaceItem
     */
    'Probability': number;
}



