/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FaceDetection } from './face-detection';

/**
 * 
 * @export
 * @interface FaceDetectionItem
 */
export interface FaceDetectionItem {
    /**
     * 
     * @type {FaceDetection}
     * @memberof FaceDetectionItem
     */
    'FaceDetection'?: FaceDetection;
}

