/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Light } from './light';
// May contain unused imports in some cases
// @ts-ignore
import type { RectangleCoordinates } from './rectangle-coordinates';

/**
 * 
 * @export
 * @interface FiberItem
 */
export interface FiberItem {
    /**
     * For UV_Fibers authenticity result type
     * @type {number}
     * @memberof FiberItem
     */
    'RectCount': number;
    /**
     * Expected fibers number. For UV_Fibers authentication result type
     * @type {number}
     * @memberof FiberItem
     */
    'ExpectedCount': number;
    /**
     * 
     * @type {Light}
     * @memberof FiberItem
     */
    'LightValue'?: Light;
    /**
     * For UV_Background authentication result type
     * @type {number}
     * @memberof FiberItem
     */
    'LightDisp'?: number;
    /**
     * Coordinates of located areas for defined fibers type
     * @type {Array<RectangleCoordinates>}
     * @memberof FiberItem
     */
    'RectArray': Array<RectangleCoordinates>;
    /**
     * Fibers width value for located areas (in pixels)
     * @type {Array<number>}
     * @memberof FiberItem
     */
    'Width': Array<number>;
    /**
     * Fibers length value for located areas (in pixels)
     * @type {Array<number>}
     * @memberof FiberItem
     */
    'Length': Array<number>;
    /**
     * Fibers value for areas (in pixels)
     * @type {Array<number>}
     * @memberof FiberItem
     */
    'Area': Array<number>;
    /**
     * Fibers color value
     * @type {Array<number>}
     * @memberof FiberItem
     */
    'ColorValues': Array<number>;
}



