/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FieldItem
 */
export interface FieldItem {
    /**
     * 
     * @type {number}
     * @memberof FieldItem
     */
    'FieldLength': number;
    /**
     * 
     * @type {number}
     * @memberof FieldItem
     */
    'FieldPos': number;
    /**
     * 
     * @type {number}
     * @memberof FieldItem
     */
    'FieldType': number;
    /**
     * 
     * @type {number}
     * @memberof FieldItem
     */
    'TEST_RESULT': number;
    /**
     * 
     * @type {number}
     * @memberof FieldItem
     */
    'ValidCheckSum': number;
    /**
     * 
     * @type {number}
     * @memberof FieldItem
     */
    'reserved': number;
}

