/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FileImage
 */
export interface FileImage {
    /**
     * 
     * @type {string}
     * @memberof FileImage
     */
    'Data': string;
    /**
     * 
     * @type {number}
     * @memberof FileImage
     */
    'Length': number;
}

