/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetTransactionsByTagResponse
 */
export interface GetTransactionsByTagResponse {
    /**
     * Transaction id
     * @type {string}
     * @memberof GetTransactionsByTagResponse
     */
    'id'?: string;
    /**
     * Transaction status
     * @type {number}
     * @memberof GetTransactionsByTagResponse
     */
    'state'?: number;
    /**
     * Last time updated
     * @type {string}
     * @memberof GetTransactionsByTagResponse
     */
    'updatedAt'?: string;
}

