/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GraphicFieldType } from './graphic-field-type';
// May contain unused imports in some cases
// @ts-ignore
import type { ImageData } from './image-data';
// May contain unused imports in some cases
// @ts-ignore
import type { RectangleCoordinates } from './rectangle-coordinates';

/**
 * Information about one graphic field - abstract class
 * @export
 * @interface GraphicField
 */
export interface GraphicField {
    /**
     * 
     * @type {RectangleCoordinates}
     * @memberof GraphicField
     */
    'FieldRect': RectangleCoordinates;
    /**
     * 
     * @type {GraphicFieldType}
     * @memberof GraphicField
     */
    'FieldType': GraphicFieldType;
    /**
     * Graphic field symbolic name
     * @type {string}
     * @memberof GraphicField
     */
    'FieldName': string;
    /**
     * 
     * @type {ImageData}
     * @memberof GraphicField
     */
    'image': ImageData;
}



