/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FileImage } from './file-image';

/**
 * 
 * @export
 * @interface GraphData
 */
export interface GraphData {
    /**
     * 
     * @type {number}
     * @memberof GraphData
     */
    'FieldType': number;
    /**
     * 
     * @type {FileImage}
     * @memberof GraphData
     */
    'File_Image': FileImage;
    /**
     * 
     * @type {number}
     * @memberof GraphData
     */
    'GraphicsType': number;
    /**
     * 
     * @type {number}
     * @memberof GraphData
     */
    'OriginDG': number;
    /**
     * 
     * @type {number}
     * @memberof GraphData
     */
    'OriginDGTag': number;
    /**
     * 
     * @type {number}
     * @memberof GraphData
     */
    'OriginEntryView': number;
    /**
     * 
     * @type {number}
     * @memberof GraphData
     */
    'OriginTagEntry': number;
}

