/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GraphicField } from './graphic-field';

/**
 * 
 * @export
 * @interface GraphicFieldsList
 */
export interface GraphicFieldsList {
    /**
     * 
     * @type {Array<GraphicField>}
     * @memberof GraphicFieldsList
     */
    'pArrayFields': Array<GraphicField>;
    /**
     * Number of pArrayFields array elements
     * @type {number}
     * @memberof GraphicFieldsList
     */
    'nFields': number;
}

