/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.  # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { GraphicFieldRect } from './graphic-field-rect';
import type { GraphicFieldRfid } from './graphic-field-rfid';

/**
 * 
 * @export
 * @interface GraphicFieldsList
 */
export interface GraphicFieldsList {
    /**
     * 
     * @type {Array<GraphicFieldRect | GraphicFieldRfid>}
     * @memberof GraphicFieldsList
     */
    pArrayFields: Array<GraphicFieldRect | GraphicFieldRfid>;
    /**
     * Number of pArrayFields array elements
     * @type {number}
     * @memberof GraphicFieldsList
     */
    nFields: number;
}
