/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 8.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GraphicFieldType } from './graphic-field-type';
// May contain unused imports in some cases
// @ts-ignore
import type { ImageData } from './image-data';
// May contain unused imports in some cases
// @ts-ignore
import type { RectangleCoordinates } from './rectangle-coordinates';

/**
 * Information about one graphic field - abstract class
 * @export
 * @interface GraphicField
 */
export interface GraphicField {
    /**
     * 
     * @type {RectangleCoordinates}
     * @memberof GraphicField
     */
    'FieldRect': RectangleCoordinates;
    /**
     * 
     * @type {GraphicFieldType}
     * @memberof GraphicField
     */
    'FieldType': GraphicFieldType;
    /**
     * Graphic field symbolic name
     * @type {string}
     * @memberof GraphicField
     */
    'FieldName': string;
    /**
     * 
     * @type {ImageData}
     * @memberof GraphicField
     */
    'image': ImageData;
}



