/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GraphicFieldType } from './graphic-field-type';
// May contain unused imports in some cases
// @ts-ignore
import type { ImageData } from './image-data';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidDataGroupTypeTag } from './rfid-data-group-type-tag';

/**
 * Information about one graphic field, which is a RFID
 * @export
 * @interface GraphicFieldRfid
 */
export interface GraphicFieldRfid {
    /**
     * 
     * @type {RfidDataGroupTypeTag}
     * @memberof GraphicFieldRfid
     */
    'RFID_OriginDG': RfidDataGroupTypeTag;
    /**
     * Index of the source record of the image with biometric information in the information data group. Only for Result.RFID_GRAPHICS result.
     * @type {number}
     * @memberof GraphicFieldRfid
     */
    'RFID_OriginDGTag': number;
    /**
     * Index of the template in the record with biometric data. Only for Result.RFID_GRAPHICS result.
     * @type {number}
     * @memberof GraphicFieldRfid
     */
    'RFID_OriginTagEntry': number;
    /**
     * Index of the variant of the biometric data template. Only for Result.RFID_GRAPHICS result.
     * @type {number}
     * @memberof GraphicFieldRfid
     */
    'RFID_OriginEntryView': number;
    /**
     * 
     * @type {GraphicFieldType}
     * @memberof GraphicFieldRfid
     */
    'FieldType': GraphicFieldType;
    /**
     * Graphic field symbolic name
     * @type {string}
     * @memberof GraphicFieldRfid
     */
    'FieldName': string;
    /**
     * 
     * @type {ImageData}
     * @memberof GraphicFieldRfid
     */
    'image': ImageData;
}



