/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HealthcheckDocumentsDatabase } from './healthcheck-documents-database';

/**
 * 
 * @export
 * @interface Healthcheck
 */
export interface Healthcheck {
    /**
     * Application name.
     * @type {string}
     * @memberof Healthcheck
     */
    'app': string;
    /**
     * Unique license identifier.
     * @type {string}
     * @memberof Healthcheck
     */
    'licenseId': string;
    /**
     * License type.
     * @type {string}
     * @memberof Healthcheck
     */
    'licenseType': string;
    /**
     * License serial number.
     * @type {string}
     * @memberof Healthcheck
     */
    'licenseSerial': string;
    /**
     * License validity date.
     * @type {string}
     * @memberof Healthcheck
     */
    'licenseValidUntil': string;
    /**
     * List of supported scenarios.
     * @type {Array<string>}
     * @memberof Healthcheck
     */
    'scenarios': Array<string>;
    /**
     * Product version.
     * @type {string}
     * @memberof Healthcheck
     */
    'version': string;
    /**
     * 
     * @type {HealthcheckDocumentsDatabase}
     * @memberof Healthcheck
     */
    'documentsDatabase'?: HealthcheckDocumentsDatabase;
}

