/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AreaContainer } from './area-container';
// May contain unused imports in some cases
// @ts-ignore
import type { ImageData } from './image-data';
// May contain unused imports in some cases
// @ts-ignore
import type { Light } from './light';
// May contain unused imports in some cases
// @ts-ignore
import type { RectangleCoordinates } from './rectangle-coordinates';
// May contain unused imports in some cases
// @ts-ignore
import type { SecurityFeatureType } from './security-feature-type';

/**
 * 
 * @export
 * @interface IdentItem
 */
export interface IdentItem {
    /**
     * 
     * @type {SecurityFeatureType}
     * @memberof IdentItem
     */
    'ElementType': SecurityFeatureType;
    /**
     * 
     * @type {Light}
     * @memberof IdentItem
     */
    'LightIndex': Light;
    /**
     * 
     * @type {RectangleCoordinates}
     * @memberof IdentItem
     */
    'Area'?: RectangleCoordinates;
    /**
     * 
     * @type {ImageData}
     * @memberof IdentItem
     */
    'Image': ImageData;
    /**
     * 
     * @type {ImageData}
     * @memberof IdentItem
     */
    'EtalonImage': ImageData;
    /**
     * 
     * @type {AreaContainer}
     * @memberof IdentItem
     */
    'AreaList'?: AreaContainer;
    /**
     * 
     * @type {number}
     * @memberof IdentItem
     */
    'ElementID'?: number;
    /**
     * 
     * @type {number}
     * @memberof IdentItem
     */
    'Result'?: number;
}



