/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CheckResult } from './check-result';
// May contain unused imports in some cases
// @ts-ignore
import type { ImageQualityCheck } from './image-quality-check';

/**
 * 
 * @export
 * @interface ImageQualityCheckList
 */
export interface ImageQualityCheckList {
    /**
     * 
     * @type {CheckResult}
     * @memberof ImageQualityCheckList
     */
    'result': CheckResult;
    /**
     * 
     * @type {Array<ImageQualityCheck>}
     * @memberof ImageQualityCheckList
     */
    'List': Array<ImageQualityCheck>;
    /**
     * Number of List array elements
     * @type {number}
     * @memberof ImageQualityCheckList
     */
    'Count': number;
}



