/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @interface ImageData
 */
export interface ImageData {
    /**
     * Base64 encoded image
     * @type {string}
     * @memberof ImageData
     */
    'image'?: string;
    /**
     * Image format
     * @type {string}
     * @memberof ImageData
     */
    'format'?: string;
}

