/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Images } from './images';

/**
 * 
 * @export
 * @interface ImagesItem
 */
export interface ImagesItem {
    /**
     * 
     * @type {Images}
     * @memberof ImagesItem
     */
    'Images': Images;
}

