/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GraphicFieldType } from './graphic-field-type';
// May contain unused imports in some cases
// @ts-ignore
import type { ImagesFieldValue } from './images-field-value';

/**
 * 
 * @export
 * @interface ImagesField
 */
export interface ImagesField {
    /**
     * Human readable field name. Do not bind to this name - use GraphicFieldType instead.
     * @type {string}
     * @memberof ImagesField
     */
    'fieldName': string;
    /**
     * 
     * @type {GraphicFieldType}
     * @memberof ImagesField
     */
    'fieldType': GraphicFieldType;
    /**
     * 
     * @type {Array<ImagesFieldValue>}
     * @memberof ImagesField
     */
    'valueList': Array<ImagesFieldValue>;
    /**
     * Field value count
     * @type {number}
     * @memberof ImagesField
     */
    'valueCount'?: number;
}



