/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ImageQualityCheckList } from './image-quality-check-list';

/**
 * 
 * @export
 * @interface ImageQualityCheckListItem
 */
export interface ImageQualityCheckListItem {
    /**
     * 
     * @type {ImageQualityCheckList}
     * @memberof ImageQualityCheckListItem
     */
    'ImageQualityCheckList': ImageQualityCheckList;
}

