/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Light } from './light';

/**
 * 
 * @export
 * @interface InDataTransactionImagesFieldValue
 */
export interface InDataTransactionImagesFieldValue {
    /**
     * 
     * @type {Light}
     * @memberof InDataTransactionImagesFieldValue
     */
    'light'?: Light;
    /**
     * 
     * @type {number}
     * @memberof InDataTransactionImagesFieldValue
     */
    'listIdx'?: number;
    /**
     * Page index of the image from input list
     * @type {number}
     * @memberof InDataTransactionImagesFieldValue
     */
    'pageIdx'?: number;
    /**
     * Image url
     * @type {string}
     * @memberof InDataTransactionImagesFieldValue
     */
    'url'?: string;
}



