/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * Video
 * @export
 * @interface InDataVideo
 */
export interface InDataVideo {
    /**
     * A free-form object containing video\'s extended attributes.
     * @type {{ [key: string]: any; }}
     * @memberof InDataVideo
     */
    'metadata'?: { [key: string]: any; };
    /**
     * Video url
     * @type {string}
     * @memberof InDataVideo
     */
    'url'?: string;
}

