/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InDataTransactionImagesFieldValue } from './in-data-transaction-images-field-value';
// May contain unused imports in some cases
// @ts-ignore
import type { InDataVideo } from './in-data-video';

/**
 * 
 * @export
 * @interface InData
 */
export interface InData {
    /**
     * 
     * @type {InDataVideo}
     * @memberof InData
     */
    'video'?: InDataVideo;
    /**
     * 
     * @type {Array<InDataTransactionImagesFieldValue>}
     * @memberof InData
     */
    'images'?: Array<InDataTransactionImagesFieldValue>;
}

