/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.  # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InData } from './in-data';
import { OutData } from './out-data';

/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {OutData}
     * @memberof InlineResponse200
     */
    OutData?: OutData;
    /**
     * 
     * @type {InData}
     * @memberof InlineResponse200
     */
    InData?: InData;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    tag?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    transactionId?: string;
}


