/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.  # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Enumeration contains the types of barcodes that can be processed
 * @export
 * @enum {string}
 */
export enum InputBarcodeType {
    /**
    * Unknown
    */
    UNKNOWN = 'bct_unknown',
    /**
    * Code 128
    */
    CODE128 = 'bct_Code128',
    /**
    * Code 39
    */
    CODE39 = 'bct_Code39',
    /**
    * EAN-8
    */
    EAN8 = 'bct_EAN8',
    /**
    * ITF
    */
    ITF = 'bct_ITF',
    /**
    * PDF417
    */
    PDF417 = 'bct_PDF417',
    /**
    * STF
    */
    STF = 'bct_STF',
    /**
    * MTF
    */
    MTF = 'bct_MTF',
    /**
    * IATA
    */
    IATA = 'bct_IATA',
    /**
    * Codabar
    */
    CODABAR = 'bct_CODABAR',
    /**
    * UPC-A
    */
    UPCA = 'bct_UPCA',
    /**
    * Code 93
    */
    CODE93 = 'bct_CODE93',
    /**
    * UPC-E
    */
    UPCE = 'bct_UPCE',
    /**
    * EAN-13
    */
    EAN13 = 'bct_EAN13',
    /**
    * QR code
    */
    QRCODE = 'bct_QRCODE',
    /**
    * Aztec code
    */
    AZTEC = 'bct_AZTEC',
    /**
    * Datamatrix
    */
    DATAMATRIX = 'bct_DATAMATRIX',
    /**
    * All 1D barcodes
    */
    ALL_1D = 'bct_ALL_1D',
    /**
    * Code 11
    */
    CODE11 = 'bct_Code11',
    /**
    * JAB code
    */
    JABCODE = 'bct_JABCODE'
}



