/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Enumeration contains the types of barcodes that can be processed
 * @export
 * @enum {string}
 */

export enum InputBarcodeType {
    /**
    * Unknown
    */
    UNKNOWN = 'bct_unknown',
    /**
    * Code 128
    */
    CODE128 = 'bct_Code128',
    /**
    * Code 39
    */
    CODE39 = 'bct_Code39',
    /**
    * EAN-8
    */
    EAN8 = 'bct_EAN8',
    /**
    * ITF
    */
    ITF = 'bct_ITF',
    /**
    * PDF417
    */
    PDF417 = 'bct_PDF417',
    /**
    * STF
    */
    STF = 'bct_STF',
    /**
    * MTF
    */
    MTF = 'bct_MTF',
    /**
    * IATA
    */
    IATA = 'bct_IATA',
    /**
    * Codabar
    */
    CODABAR = 'bct_CODABAR',
    /**
    * UPC-A
    */
    UPCA = 'bct_UPCA',
    /**
    * Code 93
    */
    CODE93 = 'bct_CODE93',
    /**
    * UPC-E
    */
    UPCE = 'bct_UPCE',
    /**
    * EAN-13
    */
    EAN13 = 'bct_EAN13',
    /**
    * QR code
    */
    QRCODE = 'bct_QRCODE',
    /**
    * Aztec code
    */
    AZTEC = 'bct_AZTEC',
    /**
    * Datamatrix
    */
    DATAMATRIX = 'bct_DATAMATRIX',
    /**
    * All 1D barcodes
    */
    ALL_1D = 'bct_ALL_1D',
    /**
    * Code 11
    */
    CODE11 = 'bct_Code11',
    /**
    * JAB code
    */
    JABCODE = 'bct_JABCODE'
}



