/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Input image quality checks for the document processing
 * @export
 * @enum {string}
 */

export enum InputImageQualityChecks {
    /**
    * Signals glare presence on the image
    */
    Glares = 'glaresCheck',
    /**
    * Signals whether image is in focus
    */
    Focus = 'focusCheck',
    /**
    * Signals if image resolution is below threshold
    */
    Resolution = 'dpiThreshold',
    /**
    * Signals if image is colorless
    */
    Colorness = 'colornessCheck',
    /**
    * Signals if document in the image has prespective distortion above threshold
    */
    Perspective = 'perspectiveCheck',
    /**
    * Signals if document is not fully present in the image
    */
    Bounds = 'documentPosition',
    /**
    * Signals if the portrait is present
    */
    Portrait = 'portraitCheck',
    /**
    * Signals if the document image is bright enough
    */
    Brightness = 'brightnessCheck',
    /**
    * Signals if the document image has occlusion
    */
    Occlusion = 'occlusionCheck'
}



