/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LicenseItem
 */
export interface LicenseItem {
    /**
     * Base64 encoded data
     * @type {string}
     * @memberof LicenseItem
     */
    'License': string;
}

