/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 8.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Image light index
 * @export
 * @enum {number}
 */

export enum Light {
    /**
    * No Light
    */
    OFF = 0,
    /**
    * Upper/lower white
    */
    WHITE_TOP = 2,
    /**
    * Side white
    */
    WHITE_SIDE = 4,
    /**
    * White
    */
    WHITE = 6,
    /**
    * Infrared
    */
    IR = 24,
    /**
    * Ultraviolet
    */
    UV = 128,
    /**
    * Axial white
    */
    AXIAL_WHITE = 3072
}



