/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Image light index
 * @export
 * @enum {number}
 */

export enum Light {
    /**
    * No Light
    */
    OFF = 0,
    /**
    * Upper/lower white
    */
    WHITE_TOP = 2,
    /**
    * Side white
    */
    WHITE_SIDE = 4,
    /**
    * White
    */
    WHITE = 6,
    /**
    * Infrared
    */
    IR = 24,
    /**
    * Ultraviolet
    */
    UV = 128,
    /**
    * Axial white
    */
    AXIAL_WHITE = 3072
}



