/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { VerifiedFieldMap } from './verified-field-map';

/**
 * 
 * @export
 * @interface ListVerifiedFields
 */
export interface ListVerifiedFields {
    /**
     * Number of pFieldMaps array elements
     * @type {number}
     * @memberof ListVerifiedFields
     */
    'Count': number;
    /**
     * 
     * @type {Array<VerifiedFieldMap>}
     * @memberof ListVerifiedFields
     */
    'pFieldMaps': Array<VerifiedFieldMap>;
    /**
     * 
     * @type {string}
     * @memberof ListVerifiedFields
     */
    'pDateFormat'?: string;
}

