/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ListVerifiedFields } from './list-verified-fields';

/**
 * 
 * @export
 * @interface ListVerifiedFieldsItem
 */
export interface ListVerifiedFieldsItem {
    /**
     * 
     * @type {ListVerifiedFields}
     * @memberof ListVerifiedFieldsItem
     */
    'ListVerifiedFields': ListVerifiedFields;
}

