/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LivenessParams
 */
export interface LivenessParams {
    /**
     * This parameter is used to enable OVI check
     * @type {boolean}
     * @memberof LivenessParams
     */
    'checkOVI'?: boolean;
    /**
     * This parameter is used to enable MLI check
     * @type {boolean}
     * @memberof LivenessParams
     */
    'checkMLI'?: boolean;
    /**
     * This parameter is used to enable Hologram detection
     * @type {boolean}
     * @memberof LivenessParams
     */
    'checkHolo'?: boolean;
    /**
     * This parameter is used to enable Electronic device detection
     * @type {boolean}
     * @memberof LivenessParams
     */
    'checkED'?: boolean;
    /**
     * This parameter is used to enable Black and white copy check
     * @type {boolean}
     * @memberof LivenessParams
     */
    'checkBlackAndWhiteCopy'?: boolean;
    /**
     * This parameter is used to enable Dynaprint check
     * @type {boolean}
     * @memberof LivenessParams
     */
    'checkDynaprint'?: boolean;
    /**
     * This parameter is used to enable Geometry check
     * @type {boolean}
     * @memberof LivenessParams
     */
    'checkGeometry'?: boolean;
}

