/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Enumeration contains identificators which determinate the level of logs detalization
 * @export
 * @enum {string}
 */

export enum LogLevel {
    /**
    * Fatal error
    */
    FATAL_ERROR = 'FatalError',
    /**
    * Error
    */
    ERROR = 'Error',
    /**
    * Warning
    */
    WARNING = 'Warning',
    /**
    * Info
    */
    INFO = 'Info',
    /**
    * Debug
    */
    DEBUG = 'Debug'
}



