/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @enum {number}
 */

export enum MDLDeviceEngagement {
    QR = 0,
    NFC = 1
}



