/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Enumeration contains possible data engagement methods with mDL
 * @export
 * @enum {number}
 */

export enum MDLDeviceEngagement {
    /**
    * Device Engagement using the QR code
    */
    QR = 0,
    /**
    * Device Engagement using the NFC module
    */
    NFC = 1
}



