/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @enum {number}
 */

export enum MDLDeviceRetrieval {
    NFC = 1,
    BLE = 2,
    WIFI_AWARE = 3
}



