/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @interface MDLItem
 */
export interface MDLItem {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof MDLItem
     */
    'MDLParsedResponse': { [key: string]: any; };
}

