/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MDLItem } from './mdlitem';
// May contain unused imports in some cases
// @ts-ignore
import type { Result } from './result';
// May contain unused imports in some cases
// @ts-ignore
import type { ResultItem } from './result-item';

/**
 * @type MDLResult
 * @export
 */
export type MDLResult = MDLItem & ResultItem;


