/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @enum {number}
 */

export enum MDLServerRetrieval {
    /**
    * Retrieval using the Web API
    */
    WEB_API = 0,
    /**
    * Retrieval using OpenID Connect
    */
    OIDC = 1
}



