/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @enum {number}
 */

export enum MeasureSystem {
    /**
    * Metric system of measurement, where things are measured in meters and grams
    */
    METRIC = 0,
    /**
    * Imperial System of Measurement, where things are measured in feet, inches and pounds
    */
    IMPERIAL = 1
}



