/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Make better MRZ detection on complex noisy backgrounds, like BW photocopy of some documents.
 * @export
 * @enum {number}
 */

export enum MrzDetectModeEnum {
    /**
    * Default detection mode
    */
    eMDM_Default = 0,
    /**
    * Apply window resizing for image binarization
    */
    eMDM_ResizeBinarizeWindow = 1,
    /**
    * Apply blur image processing before binarization
    */
    eMDM_BlurBeforeBinarization = 2
}



