/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 8.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DocumentFormat } from './document-format';
// May contain unused imports in some cases
// @ts-ignore
import type { Point } from './point';

/**
 * 
 * @export
 * @interface MrzPosition
 */
export interface MrzPosition {
    /**
     * 
     * @type {DocumentFormat}
     * @memberof MrzPosition
     */
    'docFormat': DocumentFormat;
    /**
     * Document rotation angle
     * @type {number}
     * @memberof MrzPosition
     */
    'Angle': number;
    /**
     * Document width
     * @type {number}
     * @memberof MrzPosition
     */
    'Width': number;
    /**
     * Document height
     * @type {number}
     * @memberof MrzPosition
     */
    'Height': number;
    /**
     * 
     * @type {Point}
     * @memberof MrzPosition
     */
    'Center': Point;
    /**
     * 
     * @type {Point}
     * @memberof MrzPosition
     */
    'LeftBottom': Point;
    /**
     * 
     * @type {Point}
     * @memberof MrzPosition
     */
    'LeftTop': Point;
    /**
     * 
     * @type {Point}
     * @memberof MrzPosition
     */
    'RightBottom': Point;
    /**
     * 
     * @type {Point}
     * @memberof MrzPosition
     */
    'RightTop': Point;
    /**
     * 
     * @type {number}
     * @memberof MrzPosition
     */
    'Dpi': number;
    /**
     * 
     * @type {number}
     * @memberof MrzPosition
     */
    'Inverse'?: number;
    /**
     * 
     * @type {number}
     * @memberof MrzPosition
     */
    'ObjArea'?: number;
    /**
     * 
     * @type {number}
     * @memberof MrzPosition
     */
    'ObjIntAngleDev'?: number;
    /**
     * 
     * @type {number}
     * @memberof MrzPosition
     */
    'PerspectiveTr'?: number;
    /**
     * 
     * @type {number}
     * @memberof MrzPosition
     */
    'ResultStatus'?: number;
}



