/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export enum MRZFormat {
    /**
    * 1x30
    */
    IDL = '1x30',
    /**
    * 3x30
    */
    ID1 = '3x30',
    /**
    * 2x36
    */
    ID2 = '2x36',
    /**
    * 2x44
    */
    ID3 = '2x44',
    /**
    * 1x6
    */
    CAN = '1x6',
    /**
    * 2x30
    */
    ID1_2_30 = '2x30'
}



