/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Symbol } from './symbol';

/**
 * 
 * @export
 * @interface MRZRowsItem
 */
export interface MRZRowsItem {
    /**
     * 
     * @type {number}
     * @memberof MRZRowsItem
     */
    'length': number;
    /**
     * 
     * @type {number}
     * @memberof MRZRowsItem
     */
    'maxLength': number;
    /**
     * 
     * @type {Array<Symbol>}
     * @memberof MRZRowsItem
     */
    'symbols': Array<Symbol>;
}

