/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MRZTestQuality } from './mrztest-quality';

/**
 * 
 * @export
 * @interface MRZTestQualityItem
 */
export interface MRZTestQualityItem {
    /**
     * 
     * @type {MRZTestQuality}
     * @memberof MRZTestQualityItem
     */
    'MRZTestQuality': MRZTestQuality;
}

