/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CheckResult } from './check-result';
// May contain unused imports in some cases
// @ts-ignore
import type { StringItem } from './string-item';

/**
 * 
 * @export
 * @interface MRZTestQuality
 */
export interface MRZTestQuality {
    /**
     * 
     * @type {CheckResult}
     * @memberof MRZTestQuality
     */
    'CHECK_SUMS': CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof MRZTestQuality
     */
    'CONTRAST_PRINT': CheckResult;
    /**
     * 
     * @type {number}
     * @memberof MRZTestQuality
     */
    'DOC_FORMAT': number;
    /**
     * 
     * @type {number}
     * @memberof MRZTestQuality
     */
    'MRZ_FORMAT': number;
    /**
     * 
     * @type {CheckResult}
     * @memberof MRZTestQuality
     */
    'PRINT_POSITION': CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof MRZTestQuality
     */
    'STAIN_MRZ': CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof MRZTestQuality
     */
    'SYMBOLS_PARAM': CheckResult;
    /**
     * 
     * @type {number}
     * @memberof MRZTestQuality
     */
    'StrCount': number;
    /**
     * 
     * @type {Array<StringItem>}
     * @memberof MRZTestQuality
     */
    'Strings': Array<StringItem>;
    /**
     * 
     * @type {CheckResult}
     * @memberof MRZTestQuality
     */
    'TEXTUAL_FILLING': CheckResult;
}



