/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @interface OcclusionCheckParams
 */
export interface OcclusionCheckParams {
    /**
     * The maximum size for the occluded area of a document; only those exceeding this size will be validated
     * @type {number}
     * @memberof OcclusionCheckParams
     */
    'maxOcclusionPart'?: number;
}

