/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Critical } from './critical';
// May contain unused imports in some cases
// @ts-ignore
import type { Light } from './light';
// May contain unused imports in some cases
// @ts-ignore
import type { RectangleCoordinates } from './rectangle-coordinates';
// May contain unused imports in some cases
// @ts-ignore
import type { TextFieldType } from './text-field-type';

/**
 * 
 * @export
 * @interface OCRSecurityTextItem
 */
export interface OCRSecurityTextItem {
    /**
     * 
     * @type {Critical}
     * @memberof OCRSecurityTextItem
     */
    'CriticalFlag': Critical;
    /**
     * 
     * @type {Light}
     * @memberof OCRSecurityTextItem
     */
    'LightType': Light;
    /**
     * 
     * @type {RectangleCoordinates}
     * @memberof OCRSecurityTextItem
     */
    'FieldRect': RectangleCoordinates;
    /**
     * Same as Result type, but used for safe parsing of not-described values. See Result type.
     * @type {number}
     * @memberof OCRSecurityTextItem
     */
    'EtalonResultType': number;
    /**
     * 
     * @type {TextFieldType}
     * @memberof OCRSecurityTextItem
     */
    'EtalonFieldType': TextFieldType;
    /**
     * 
     * @type {Light}
     * @memberof OCRSecurityTextItem
     */
    'EtalonLightType': Light;
    /**
     * 
     * @type {RectangleCoordinates}
     * @memberof OCRSecurityTextItem
     */
    'EtalonFieldRect': RectangleCoordinates;
    /**
     * 
     * @type {string}
     * @memberof OCRSecurityTextItem
     */
    'SecurityTextResultOCR': string;
    /**
     * 
     * @type {string}
     * @memberof OCRSecurityTextItem
     */
    'EtalonResultOCR': string;
    /**
     * 
     * @type {number}
     * @memberof OCRSecurityTextItem
     */
    'Reserved1'?: number;
    /**
     * 
     * @type {number}
     * @memberof OCRSecurityTextItem
     */
    'Reserved2'?: number;
}



