/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OneCandidate } from './one-candidate';

/**
 * 
 * @export
 * @interface OneCandidateItem
 */
export interface OneCandidateItem {
    /**
     * 
     * @type {OneCandidate}
     * @memberof OneCandidateItem
     */
    'OneCandidate': OneCandidate;
    /**
     * 
     * @type {string}
     * @memberof OneCandidateItem
     */
    'XML_buffer'?: string;
}

