/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RectangleCoordinates } from './rectangle-coordinates';

/**
 * 
 * @export
 * @interface OriginalSymbol
 */
export interface OriginalSymbol {
    /**
     * Unicode symbol code
     * @type {number}
     * @memberof OriginalSymbol
     */
    'code': number;
    /**
     * Probability of correctness reading of a single character
     * @type {number}
     * @memberof OriginalSymbol
     */
    'probability': number;
    /**
     * 
     * @type {RectangleCoordinates}
     * @memberof OriginalSymbol
     */
    'rect'?: RectangleCoordinates;
}

