/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GraphicFieldType } from './graphic-field-type';
// May contain unused imports in some cases
// @ts-ignore
import type { Light } from './light';

/**
 * 
 * @export
 * @interface OutDataTransactionImagesFieldValue
 */
export interface OutDataTransactionImagesFieldValue {
    /**
     * 
     * @type {GraphicFieldType}
     * @memberof OutDataTransactionImagesFieldValue
     */
    'fieldType'?: GraphicFieldType;
    /**
     * 
     * @type {Light}
     * @memberof OutDataTransactionImagesFieldValue
     */
    'light'?: Light;
    /**
     * 
     * @type {number}
     * @memberof OutDataTransactionImagesFieldValue
     */
    'listIdx'?: number;
    /**
     * Page index of the image from input list
     * @type {number}
     * @memberof OutDataTransactionImagesFieldValue
     */
    'pageIdx'?: number;
    /**
     * Image url
     * @type {string}
     * @memberof OutDataTransactionImagesFieldValue
     */
    'url'?: string;
}



