/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OutDataTransactionImagesFieldValue } from './out-data-transaction-images-field-value';

/**
 * 
 * @export
 * @interface OutData
 */
export interface OutData {
    /**
     * Response url
     * @type {string}
     * @memberof OutData
     */
    'url'?: string;
    /**
     * 
     * @type {Array<OutDataTransactionImagesFieldValue>}
     * @memberof OutData
     */
    'images'?: Array<OutDataTransactionImagesFieldValue>;
}

