/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BarcodeType } from './barcode-type';
// May contain unused imports in some cases
// @ts-ignore
import type { BcPDF417INFO } from './bc-pdf417-info';
// May contain unused imports in some cases
// @ts-ignore
import type { BcROIDETECT } from './bc-roidetect';
// May contain unused imports in some cases
// @ts-ignore
import type { DataModule } from './data-module';
// May contain unused imports in some cases
// @ts-ignore
import type { TextFieldType } from './text-field-type';

/**
 * 
 * @export
 * @interface PArrayField
 */
export interface PArrayField {
    /**
     * 
     * @type {number}
     * @memberof PArrayField
     */
    'bcAngle_DETECT': number;
    /**
     * 
     * @type {number}
     * @memberof PArrayField
     */
    'bcCodeResult': number;
    /**
     * 
     * @type {number}
     * @memberof PArrayField
     */
    'bcCountModule': number;
    /**
     * 
     * @type {Array<DataModule>}
     * @memberof PArrayField
     */
    'bcDataModule': Array<DataModule>;
    /**
     * 
     * @type {BcPDF417INFO}
     * @memberof PArrayField
     */
    'bcPDF417INFO'?: BcPDF417INFO;
    /**
     * 
     * @type {BcROIDETECT}
     * @memberof PArrayField
     */
    'bcROI_DETECT': BcROIDETECT;
    /**
     * 
     * @type {number}
     * @memberof PArrayField
     */
    'bcTextDecoderTypes'?: number;
    /**
     * 
     * @type {TextFieldType}
     * @memberof PArrayField
     */
    'bcTextFieldType'?: TextFieldType;
    /**
     * 
     * @type {BarcodeType}
     * @memberof PArrayField
     */
    'bcType_DECODE': BarcodeType;
    /**
     * 
     * @type {number}
     * @memberof PArrayField
     */
    'bcType_DETECT': number;
}



