/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @interface ParsedData
 */
export interface ParsedData {
    /**
     * 
     * @type {Array<number>}
     * @memberof ParsedData
     */
    'ParsingNotifications'?: Array<number>;
}

