/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 8.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The enumeration contains error codes that can return during the RFID chip processing.
 * @export
 * @enum {number}
 */

export enum ParsingErrorCodes {
    /**
    * OK
    */
    errLDS_Ok = 1,
    /**
    * ASN: Incorrect data
    */
    errLDS_ASN_IncorrectData = 2147483649,
    /**
    * ASN: Not enough data
    */
    errLDS_ASN_NotEnoughData = 2147483650,
    /**
    * ASN: Contents unexpected data
    */
    errLDS_ASN_Contents_UnexpectedData = 2147483651,
    /**
    * ASN Signed data: Incorrect data
    */
    errLDS_ASN_SignedData_IncorrectData = 2147483656,
    /**
    * ASN Signed data: Encap contents incorrect data
    */
    errLDS_ASN_SignedData_EncapContents_IncorrectData = 2147483657,
    /**
    * ASN Signed data: Version incorrect data
    */
    errLDS_ASN_SignedData_Version_IncorrectData = 2147483658,
    /**
    * ASN Signed data: Digest algorithms incorrect data
    */
    errLDS_ASN_SignedData_DigestAlgorithms_IncorrectData = 2147483665,
    /**
    * ASN LDS object: Incorrect data
    */
    errLDS_ASN_LDSObject_IncorrectData = 2147483667,
    /**
    * ASN LDS object: Version incorrect data
    */
    errLDS_ASN_LDSObject_Version_IncorrectData = 2147483668,
    /**
    * ASN LDS object: Digest algorithm incorrect data
    */
    errLDS_ASN_LDSObject_DigestAlgorithm_IncorrectData = 2147483669,
    /**
    * ASN LDS object: DG hashes incorrect data
    */
    errLDS_ASN_LDSObject_DGHashes_IncorrectData = 2147483670,
    /**
    * ASN LDS object: Version info incorrect data
    */
    errLDS_ASN_LDSObject_VersionInfo_IncorrectData = 2147483666,
    /**
    * ASN Certificate: Incorrect data
    */
    errLDS_ASN_Certificate_IncorrectData = 2147483671,
    /**
    * ASN Certificate: Version incorrect data
    */
    errLDS_ASN_Certificate_Version_IncorrectData = 2147483672,
    /**
    * ASN Certificate: SN incorrect data
    */
    errLDS_ASN_Certificate_SN_IncorrectData = 2147483673,
    /**
    * ASN Certificate: Signature incorrect data
    */
    errLDS_ASN_Certificate_Signature_IncorrectData = 2147483674,
    /**
    * ASN Certificate: Issuer incorrect data
    */
    errLDS_ASN_Certificate_Issuer_IncorrectData = 2147483675,
    /**
    * ASN Certificate: Validity incorrect data
    */
    errLDS_ASN_Certificate_Validity_IncorrectData = 2147483676,
    /**
    * ASN Certificate: Subject incorrect data
    */
    errLDS_ASN_Certificate_Subject_IncorrectData = 2147483677,
    /**
    * ASN Certificate: Subject PK incorrect data
    */
    errLDS_ASN_Certificate_SubjectPK_IncorrectData = 2147483678,
    /**
    * ASN Certificate: Extensions incorrect data
    */
    errLDS_ASN_Certificate_Extensions_IncorrectData = 2147483679,
    /**
    * ASN Signer info: Incorrect data
    */
    errLDS_ASN_SignerInfo_IncorrectData = 2147483680,
    /**
    * ASN Signer info: Version incorrect data
    */
    errLDS_ASN_SignerInfo_Version_IncorrectData = 2147483681,
    /**
    * ASN Signer info: SID incorrect data
    */
    errLDS_ASN_SignerInfo_SID_IncorrectData = 2147483682,
    /**
    * ASN Signer info: Digest algorithms incorrect data
    */
    errLDS_ASN_SignerInfo_DigestAlg_IncorrectData = 2147483683,
    /**
    * ASN Signer info: Signed attributes incorrect data
    */
    errLDS_ASN_SignerInfo_SignedAttrs_IncorrectData = 2147483684,
    /**
    * ASN Signer info: Sign algorithms incorrect data
    */
    errLDS_ASN_SignerInfo_SignAlg_IncorrectData = 2147483685,
    /**
    * ASN Signer info: Signature incorrect data
    */
    errLDS_ASN_SignerInfo_Signature_IncorrectData = 2147483686,
    /**
    * ASN Signer info: Unsigned attributes incorrect data
    */
    errLDS_ASN_SignerInfo_UnsignedAttrs_IncorrectData = 2147483687,
    /**
    * ASN DTC Signer info: Incorrect data
    */
    errLDS_ASN_DTC_SignerInfo_IncorrectData = 2147483712,
    /**
    * ASN DTC Signer info: Certificate incorrect data
    */
    errLDS_ASN_DTC_SignerInfo_Certificate_IncorrectData = 2147483713,
    /**
    * ASN DTC Signer info: Digest algorithms incorrect data
    */
    errLDS_ASN_DTC_SignerInfo_DigestAlg_IncorrectData = 2147483714,
    /**
    * ASN DTC Signer info: Signed attributes incorrect data
    */
    errLDS_ASN_DTC_SignerInfo_SignedAttrs_IncorrectData = 2147483715,
    /**
    * ASN DTC Signer info: Sign algorithms incorrect data
    */
    errLDS_ASN_DTC_SignerInfo_SignAlg_IncorrectData = 2147483716,
    /**
    * ASN DTC Signer info: Signature incorrect data
    */
    errLDS_ASN_DTC_SignerInfo_Signature_IncorrectData = 2147483717,
    /**
    * ASN DTC Security info: Incorrect data
    */
    errLDS_ASN_DTC_SecurityInfo_IncorrectData = 2147483718,
    /**
    * ASN DTC Content info: Incorrect data
    */
    errLDS_ASN_DTC_ContentInfo_IncorrectData = 2147483719,
    /**
    * ICAO LDS object: Unsupported digest algorithm
    */
    errLDS_ICAO_LDSObject_UnsupportedDigestAlgorithm = 2147483696,
    /**
    * ICAO Signed data: Signer info empty
    */
    errLDS_ICAO_SignedData_SignerInfos_Empty = 2147483697,
    /**
    * ICAO Signer info: Unsupported digest algorithm
    */
    errLDS_ICAO_SignerInfo_UnsupportedDigestAlgorithm = 2147483698,
    /**
    * ICAO Signer info: Unsupported signature algorithm
    */
    errLDS_ICAO_SignerInfo_UnsupportedSignatureAlgorithm = 2147483699,
    /**
    * ICAO Signer info: Message digest error
    */
    errLDS_ICAO_SignerInfo_MessageDigestError = 2147483700,
    /**
    * ICAO Signer info: Signed attributes missed
    */
    errLDS_ICAO_SignerInfo_SignedAttrs_Missed = 2147483702,
    /**
    * Auth: Signer info cannot find certificate
    */
    errLDS_Auth_SignerInfo_CantFindCertificate = 2147483701,
    /**
    * Auth: Error
    */
    errLDS_Auth_Error = 2147483728,
    /**
    * Auth: Unsupported signature algorithm
    */
    errLDS_Auth_UnsupportedSignatureAlgorithm = 2147483729,
    /**
    * Auth: Unsupported public key algorithm
    */
    errLDS_Auth_UnsupportedPublicKeyAlgorithm = 2147483730,
    /**
    * Auth: Messed algorithms
    */
    errLDS_Auth_MessedAlgorithms = 2147483731,
    /**
    * Auth: Public key data invalid
    */
    errLDS_Auth_PublicKeyDataInvalid = 2147483732,
    /**
    * Auth: Algorithm parameters data invalid
    */
    errLDS_Auth_AlgorithmParametersDataInvalid = 2147483733,
    /**
    * Auth: Signature data invalid
    */
    errLDS_Auth_SignatureDataInvalid = 2147483734,
    /**
    * Auth: Unsupported digest algorithm
    */
    errLDS_Auth_UnsupportedDigestAlgorithm = 2147483735,
    /**
    * Auth: Signature data incorrect
    */
    errLDS_Auth_SignatureDataIncorrect = 2147483736,
    /**
    * Auth: Algorithm parameters not defined
    */
    errLDS_Auth_AlgorithmParametersNotDefined = 2147483737,
    /**
    * Auth: Signature check failed
    */
    errLDS_Auth_SignatureCheckFailed = 2147483738,
    /**
    * DG: Wrong Tag
    */
    errLDS_DG_WrongTag = 2147483760,
    /**
    * DG: Contents unexpected data
    */
    errLDS_DG_Contents_UnexpectedData = 2147483761,
    /**
    * BAP: Symmetric Cypher Cannot Initialize
    */
    errLDS_BAP_SymmetricCypher_CantInitialize = 2164260881,
    /**
    * PACE: Info Not Available
    */
    errLDS_PACE_Info_NotAvailable = 2164260896,
    /**
    * PACE: Symmetric Cypher Cannot Initialize
    */
    errLDS_PACE_SymmetricCypher_CantInitialize = 2164260897,
    /**
    * PACE: Key Agreement Cannot Initialize
    */
    errLDS_PACE_KeyAgreement_CantInitialize = 2164260898,
    /**
    * PACE: Ephemeral Keys Cannot Create
    */
    errLDS_PACE_EphemeralKeys_CantCreate = 2164260899,
    /**
    * PACE: Mapping Cannot Decode Nonce
    */
    errLDS_PACE_Mapping_CantDecodeNonce = 2164260900,
    /**
    * PACE: Shared Secret Cannot Create
    */
    errLDS_PACE_SharedSecret_CantCreate = 2164260901,
    /**
    * PACE: Domain Params Unsupported Format
    */
    errLDS_PACE_DomainParams_UnsupportedFormat = 2164260902,
    /**
    * PACE: Ephemeral Keys Incorrect
    */
    errLDS_PACE_EphemeralKeys_Incorrect = 2164260903,
    /**
    * PACE: Mapping Ephemeral Keys Incorrect
    */
    errLDS_PACE_Mapping_EphemeralKeys_Incorrect = 2164260904,
    /**
    * PACE: Mapping Cannot Perform
    */
    errLDS_PACE_Mapping_CantPerform = 2164260905,
    /**
    * PACE: Non-Matching Auth Tokens
    */
    errLDS_PACE_NonMatchingAuthTokens = 2164260906,
    /**
    * PACE: CAM data incorrect
    */
    errLDS_PACE_CAM_Data_Incorrect = 2164260907,
    /**
    * PACE: CAM data cannot verify
    */
    errLDS_PACE_CAM_Data_CantVerify = 2164260908,
    /**
    * PACE: CAM data non-matching
    */
    errLDS_PACE_CAM_Data_NonMatching = 2164260909,
    /**
    * PACE: IM scheme incorrect
    */
    errLDS_PACE_IM_Scheme_Incorrect = 2164260910,
    /**
    * PACE: Random mapping failed
    */
    errLDS_PACE_IM_RandomMapping_Failed = 2164260911,
    /**
    * CA: Cannot Find Public Key
    */
    errLDS_CA_CantFindPublicKey = 2164260912,
    /**
    * CA: Cannot Find Info
    */
    errLDS_CA_CantFindInfo = 2164260913,
    /**
    * CA: Incorrect Version
    */
    errLDS_CA_IncorrectVersion = 2164260914,
    /**
    * CA: Cannot Find Domain Parameters
    */
    errLDS_CA_CantFindDomainParameters = 2164260915,
    /**
    * CA: Key Agreement Cannot Initialize
    */
    errLDS_CA_KeyAgreement_CantInitialize = 2164260916,
    /**
    * CA: Public Key Unsupported Algorithm
    */
    errLDS_CA_PublicKey_UnsupportedAlgorithm = 2164260917,
    /**
    * CA: Ephemeral Keys Cannot Create
    */
    errLDS_CA_EphemeralKeys_CantCreate = 2164260918,
    /**
    * CA: Shared Secret Cannot Create
    */
    errLDS_CA_SharedSecret_CantCreate = 2164260919,
    /**
    * CA: Non-Matching Auth Tokens
    */
    errLDS_CA_NonMatchingAuthTokens = 2164260920,
    /**
    * TA: Incorrect Version
    */
    errLDS_TA_IncorrectVersion = 2164260928,
    /**
    * TA: Cannot Build Certificate Chain
    */
    errLDS_TA_CantBuildCertificateChain = 2164260929,
    /**
    * TA: Cannot Find IS Private Key
    */
    errLDS_TA_CantFindISPrivateKey = 2164260930,
    /**
    * TA: Public Key Unsupported Algorithm
    */
    errLDS_TA_PublicKey_UnsupportedAlgorithm = 2164260931,
    /**
    * TA: Signature Building Error
    */
    errLDS_TA_SignatureBuildingError = 2164260932,
    /**
    * TA: Invalid Key Algorithm Parameters
    */
    errLDS_TA_InvalidKeyAlgorithmParameters = 2164260933,
    /**
    * AA: Public Key Unsupported Algorithm
    */
    errLDS_AA_PublicKey_UnsupportedAlgorithm = 2164260944,
    /**
    * AA: Public Key Incorrect Data
    */
    errLDS_AA_PublicKey_IncorrectData = 2164260945,
    /**
    * AA: Public Key Incorrect Parameters
    */
    errLDS_AA_PublicKey_IncorrectParameters = 2164260946,
    /**
    * AA: Public Key Undefined Parameters
    */
    errLDS_AA_PublicKey_UndefinedParameters = 2164260947,
    /**
    * AA: Signature Incorrect Data
    */
    errLDS_AA_Signature_IncorrectData = 2164260948,
    /**
    * AA: Unsupported recovery scheme
    */
    errLDS_AA_UnsupportedRecoveryScheme = 2164260949,
    /**
    * AA: Incorrect Trailer
    */
    errLDS_AA_IncorrectTrailer = 2164260950,
    /**
    * AA: Unsupported Digest Algorithm
    */
    errLDS_AA_UnsupportedDigestAlgorithm = 2164260951,
    /**
    * RI: Sector Key Cannot Find
    */
    errLDS_RI_SectorKey_CantFind = 2164260976,
    /**
    * RI: Sector Key Incorrect Data
    */
    errLDS_RI_SectorKey_IncorrectData = 2164260977,
    /**
    * RI: Sector Key Incomplete Data
    */
    errLDS_RI_SectorKey_IncompleteData = 2164260978,
    /**
    * CV Certificate: Missing mandatory data PK
    */
    errLDS_CV_Certificate_MissingMandatoryData_PK = 2164260960,
    /**
    * CV Certificate: Public key unsupported
    */
    errLDS_CV_Certificate_PublicKey_Unsupported = 2164260962,
    /**
    * CV Certificate: CHAT unsupported terminal type
    */
    errLDS_CV_Certificate_CHAT_UnsupportedTerminalType = 2164260963,
    /**
    * CV Certificate: Private key unsupported
    */
    errLDS_CV_Certificate_PrivateKey_Unsupported = 2164260964,
    /**
    * CV Certificate: Private key invalid params
    */
    errLDS_CV_Certificate_PrivateKey_InvalidParams = 2164260965,
    /**
    * CV Certificate: Incorrect data
    */
    errLDS_CV_Certificate_IncorrectData = 2164261216,
    /**
    * CV Certificate: CPI incorrect data
    */
    errLDS_CV_Certificate_CPI_IncorrectData = 2164261217,
    /**
    * CV Certificate: CAR incorrect data
    */
    errLDS_CV_Certificate_CAR_IncorrectData = 2164261218,
    /**
    * CV Certificate: Public key incorrect data
    */
    errLDS_CV_Certificate_PublicKey_IncorrectData = 2164261219,
    /**
    * CV Certificate: CHR incorrect data
    */
    errLDS_CV_Certificate_CHR_IncorrectData = 2164261220,
    /**
    * CV Certificate: CHAT incorrect data
    */
    errLDS_CV_Certificate_CHAT_IncorrectData = 2164261221,
    /**
    * CV Certificate: Valid from incorrect data
    */
    errLDS_CV_Certificate_ValidFrom_IncorrectData = 2164261222,
    /**
    * CV Certificate: Valid to incorrect data
    */
    errLDS_CV_Certificate_ValidTo_IncorrectData = 2164261223,
    /**
    * CV Certificate: Extensions incorrect data
    */
    errLDS_CV_Certificate_Extensions_IncorrectData = 2164261224,
    /**
    * CV Certificate: Private key incorrect data
    */
    errLDS_CV_Certificate_PrivateKey_IncorrectData = 2164261225,
    /**
    * CV Certificate: Private key missing
    */
    errLDS_CV_Certificate_PrivateKey_Missing = 2164261226,
    /**
    * VDS: Unsupported version
    */
    errLDS_VDS_UnsupportedVersion = 2164261376,
    /**
    * VDS: Issuing country size
    */
    errLDS_VDS_Issuing_Country_Size = 2164261377,
    /**
    * VDS: Issuing country incorrect data
    */
    errLDS_VDS_Issuing_Country_IncorrectData = 2164261378,
    /**
    * VDS: Signature certificate size
    */
    errLDS_VDS_Signer_Certificate_Size = 2164261379,
    /**
    * VDS: Signature certificate data
    */
    errLDS_VDS_Signer_Certificate_Data = 2164261380,
    /**
    * VDS: Signature incorrect data
    */
    errLDS_VDS_Signature_IncorrectData = 2164261381,
    /**
    * VDS: Incorrect data
    */
    errLDS_VDS_NC_IncorrectData = 2164261632,
    /**
    * VDS: Missing or incorrect data
    */
    errLDS_VDS_NC_MissingOrIncorrect_Data = 2164261633,
    /**
    * VDS: Missing or incorrect header
    */
    errLDS_VDS_NC_MissingOrIncorrect_Header = 2164261634,
    /**
    * VDS: Missing or incorrect type
    */
    errLDS_VDS_NC_MissingOrIncorrect_Type = 2164261635,
    /**
    * VDS: Missing or incorrect version
    */
    errLDS_VDS_NC_MissingOrIncorrect_Version = 2164261636,
    /**
    * VDS: Missing or incorrect issuing country
    */
    errLDS_VDS_NC_MissingOrIncorrect_IssuingCountry = 2164261637,
    /**
    * VDS: Missing or incorrect message
    */
    errLDS_VDS_NC_MissingOrIncorrect_Message = 2164261638,
    /**
    * VDS: Missing or incorrect signature
    */
    errLDS_VDS_NC_MissingOrIncorrect_Signature = 2164261639,
    /**
    * VDS: Missing or incorrect signature algorithm
    */
    errLDS_VDS_NC_MissingOrIncorrect_SigAlgorithm = 2164261640,
    /**
    * VDS: Missing or incorrect certificate
    */
    errLDS_VDS_NC_MissingOrIncorrect_Certificate = 2164261641,
    /**
    * VDS: Missing or incorrect signature value
    */
    errLDS_VDS_NC_MissingOrIncorrect_SigValue = 2164261642
}



