/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PerDocumentConfig
 */
export interface PerDocumentConfig {
    /**
     * Specific template IDs, for which apply current custom configuration
     * @type {Array<number>}
     * @memberof PerDocumentConfig
     */
    'docID'?: Array<number>;
    /**
     * Contains items from AuthenticityResultType as sum via OR operation
     * @type {number}
     * @memberof PerDocumentConfig
     */
    'excludeAuthChecks'?: number;
}

