/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ImageData } from './image-data';
// May contain unused imports in some cases
// @ts-ignore
import type { Light } from './light';
// May contain unused imports in some cases
// @ts-ignore
import type { RawImageContainerList } from './raw-image-container-list';
// May contain unused imports in some cases
// @ts-ignore
import type { RectangleCoordinates } from './rectangle-coordinates';

/**
 * 
 * @export
 * @interface PhotoIdentItem
 */
export interface PhotoIdentItem {
    /**
     * 
     * @type {Light}
     * @memberof PhotoIdentItem
     */
    'LightIndex': Light;
    /**
     * 
     * @type {RectangleCoordinates}
     * @memberof PhotoIdentItem
     */
    'Area': RectangleCoordinates;
    /**
     * 
     * @type {ImageData}
     * @memberof PhotoIdentItem
     */
    'SourceImage': ImageData;
    /**
     * 
     * @type {RawImageContainerList}
     * @memberof PhotoIdentItem
     */
    'ResultImages': RawImageContainerList;
    /**
     * 
     * @type {number}
     * @memberof PhotoIdentItem
     */
    'FieldTypesCount'?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof PhotoIdentItem
     */
    'FieldTypesList'?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof PhotoIdentItem
     */
    'Step'?: number;
    /**
     * 
     * @type {number}
     * @memberof PhotoIdentItem
     */
    'Angle'?: number;
    /**
     * 
     * @type {number}
     * @memberof PhotoIdentItem
     */
    'Reserved3'?: number;
}



