/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @interface PID
 */
export interface PID {
    /**
     * 
     * @type {string}
     * @memberof PID
     */
    'dob'?: string;
    /**
     * 
     * @type {string}
     * @memberof PID
     */
    'i'?: string;
    /**
     * 
     * @type {string}
     * @memberof PID
     */
    'n'?: string;
    /**
     * 
     * @type {string}
     * @memberof PID
     */
    'sex'?: string;
}

