/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Point } from './point';

/**
 * 
 * @export
 * @interface PointsContainer
 */
export interface PointsContainer {
    /**
     * 
     * @type {number}
     * @memberof PointsContainer
     */
    'PointCount'?: number;
    /**
     * 
     * @type {Array<Point>}
     * @memberof PointsContainer
     */
    'PointsList': Array<Point>;
}

