/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContainerList } from './container-list';
// May contain unused imports in some cases
// @ts-ignore
import type { ProcessingStatus } from './processing-status';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidLocation } from './rfid-location';
// May contain unused imports in some cases
// @ts-ignore
import type { TransactionInfo } from './transaction-info';

/**
 * 
 * @export
 * @interface ProcessResponse
 */
export interface ProcessResponse {
    /**
     * 
     * @type {RfidLocation}
     * @memberof ProcessResponse
     */
    'ChipPage': RfidLocation;
    /**
     * 
     * @type {number}
     * @memberof ProcessResponse
     */
    'CoreLibResultCode'?: number;
    /**
     * 
     * @type {ProcessingStatus}
     * @memberof ProcessResponse
     */
    'ProcessingFinished': ProcessingStatus;
    /**
     * 
     * @type {ContainerList}
     * @memberof ProcessResponse
     */
    'ContainerList': ContainerList;
    /**
     * 
     * @type {TransactionInfo}
     * @memberof ProcessResponse
     */
    'TransactionInfo': TransactionInfo;
    /**
     * Base64 encoded transaction processing log
     * @type {string}
     * @memberof ProcessResponse
     */
    'log'?: string;
    /**
     * Free-form object provided in request. See passBackObject property of ProcessRequest.
     * @type {{ [key: string]: any; }}
     * @memberof ProcessResponse
     */
    'passBackObject'?: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof ProcessResponse
     */
    'morePagesAvailable': number;
    /**
     * Time the document processing has taken, ms.
     * @type {number}
     * @memberof ProcessResponse
     */
    'elapsedTime': number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ProcessResponse
     */
    'metadata'?: { [key: string]: any; };
}



