/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @enum {number}
 */

export enum ProcessingStatus {
    /**
    * Processing was not finished
    */
    NOT_FINISHED = 0,
    /**
    * Processing finished
    */
    FINISHED = 1,
    /**
    * Processing finished by timeout
    */
    TIMEOUT = 2
}



