/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ParsingNotificationCodes } from './parsing-notification-codes';

/**
 * Params for the RFID chip data reprocessing
 * @export
 * @interface ProcessParamsRfid
 */
export interface ProcessParamsRfid {
    /**
     * A list of notification codes that should be ignored during passive authentication (PA)
     * @type {Array<ParsingNotificationCodes>}
     * @memberof ProcessParamsRfid
     */
    'paIgnoreNotificationCodes'?: Array<ParsingNotificationCodes>;
}

