/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ImageData } from './image-data';
// May contain unused imports in some cases
// @ts-ignore
import type { Light } from './light';

/**
 * 
 * @export
 * @interface ProcessRequestImage
 */
export interface ProcessRequestImage {
    /**
     * 
     * @type {ImageData}
     * @memberof ProcessRequestImage
     */
    'ImageData'?: ImageData;
    /**
     * 
     * @type {Light}
     * @memberof ProcessRequestImage
     */
    'light'?: Light;
    /**
     * page/image number
     * @type {number}
     * @memberof ProcessRequestImage
     */
    'page_idx'?: number;
}



