/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @interface ProcessSystemInfo
 */
export interface ProcessSystemInfo {
    /**
     * Base64 encoded license file
     * @type {string}
     * @memberof ProcessSystemInfo
     */
    'license'?: string;
    /**
     * For internal use. Demo-sites recaptcha token.
     * @type {string}
     * @memberof ProcessSystemInfo
     */
    'recaptcha_token'?: string;
}

