/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ImageData } from './image-data';

/**
 * 
 * @export
 * @interface RawImageContainerList
 */
export interface RawImageContainerList {
    /**
     * 
     * @type {number}
     * @memberof RawImageContainerList
     */
    'Count': number;
    /**
     * 
     * @type {Array<ImageData>}
     * @memberof RawImageContainerList
     */
    'Images': Array<ImageData>;
}

