/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * Coordinates of the rectangle region on a document image(result type 1). Represented by two points - (left, top) + (right, bottom)
 * @export
 * @interface RectangleCoordinates
 */
export interface RectangleCoordinates {
    /**
     * 
     * @type {number}
     * @memberof RectangleCoordinates
     */
    'left': number;
    /**
     * 
     * @type {number}
     * @memberof RectangleCoordinates
     */
    'top': number;
    /**
     * 
     * @type {number}
     * @memberof RectangleCoordinates
     */
    'right': number;
    /**
     * 
     * @type {number}
     * @memberof RectangleCoordinates
     */
    'bottom': number;
}

