/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RFIDDocVisualExtendedInfo } from './rfiddoc-visual-extended-info';

/**
 * 
 * @export
 * @interface RFIDDocVisualExtendedInfoItem
 */
export interface RFIDDocVisualExtendedInfoItem {
    /**
     * 
     * @type {RFIDDocVisualExtendedInfo}
     * @memberof RFIDDocVisualExtendedInfoItem
     */
    'DocVisualExtendedInfo': RFIDDocVisualExtendedInfo;
}

