/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Enumeration contains a set of constants specifying the rate of data exchange between the reader and the RFID-chip
 * @export
 * @enum {number}
 */

export enum RfidBaudRate {
    /**
    * Unknown
    */
    UNKNOWN = 0,
    /**
    * 106 bits/s
    */
    RFBR_106 = 1,
    /**
    * 212 bits/s
    */
    RFBR_212 = 2,
    /**
    * 424 bits/s
    */
    RFBR_424 = 4,
    /**
    * 848 bits/s
    */
    RFBR_848 = 8,
    /**
    * 1695 bits/s
    */
    RFBR_1695 = 16,
    /**
    * 3390 bits/s
    */
    RFBR_3390 = 32,
    /**
    * 6780 bits/s
    */
    RFBR_6780 = 64
}



