/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RFIDDocVisualExtendedFieldItem
 */
export interface RFIDDocVisualExtendedFieldItem {
    /**
     * 
     * @type {number}
     * @memberof RFIDDocVisualExtendedFieldItem
     */
    'OriginDG': number;
    /**
     * 
     * @type {number}
     * @memberof RFIDDocVisualExtendedFieldItem
     */
    'OriginDGTag'?: number;
    /**
     * Record index of the text field source in the data group
     * @type {number}
     * @memberof RFIDDocVisualExtendedFieldItem
     */
    'OriginTagEntry': number;
    /**
     * 
     * @type {number}
     * @memberof RFIDDocVisualExtendedFieldItem
     */
    'OriginEntryView'?: number;
}

