/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RFIDDocVisualExtendedField } from './rfiddoc-visual-extended-field';

/**
 * Container for extracted text fields. Fields are identified by type and language
 * @export
 * @interface RFIDDocVisualExtendedInfo
 */
export interface RFIDDocVisualExtendedInfo {
    /**
     * Number of pArrayFields array elements
     * @type {number}
     * @memberof RFIDDocVisualExtendedInfo
     */
    'nFields': number;
    /**
     * 
     * @type {Array<RFIDDocVisualExtendedField>}
     * @memberof RFIDDocVisualExtendedInfo
     */
    'pArrayFields': Array<RFIDDocVisualExtendedField>;
}

