/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * Enumeration contains a set of constants that define the type of application within the context of the communication session with electronic document
 * @export
 * @enum {number}
 */

export enum RfidApplicationType {
    /**
    * Not defined
    */
    UNSPECIFIED = 0,
    /**
    * ePassport application
    */
    E_PASSPORT = 1,
    /**
    * eID application
    */
    E_ID = 2,
    /**
    * eSign application
    */
    E_SIGN = 3,
    /**
    * eDL application
    */
    E_DL = 4,
    /**
    * TravelRecords application
    */
    LDS2_TravelRecords = 5,
    /**
    * VisaRecords application
    */
    LDS2_VisaRecords = 6,
    /**
    * AddBiometrics application
    */
    LDS2_AddBiometrics = 7,
    /**
    * Digital Travel Credentials
    */
    eDTC_PC = 8,
    /**
    * Master File
    */
    ROOT_FILES = 0
}



