/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ParsingNotificationCodes } from './parsing-notification-codes';
// May contain unused imports in some cases
// @ts-ignore
import type { RFIDErrorCodes } from './rfiderror-codes';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidAccessControlProcedureType } from './rfid-access-control-procedure-type';

/**
 * Structure is used to describe the results of a single authentication procedure or a procedure of secure data access within the context of the communication session with electronic document
 * @export
 * @interface RfidAccessControlInfo
 */
export interface RfidAccessControlInfo {
    /**
     * 
     * @type {RfidAccessControlProcedureType}
     * @memberof RfidAccessControlInfo
     */
    'Type': RfidAccessControlProcedureType;
    /**
     * 
     * @type {RFIDErrorCodes}
     * @memberof RfidAccessControlInfo
     */
    'Status': RFIDErrorCodes;
    /**
     * Index of the active variant of the procedure
     * @type {number}
     * @memberof RfidAccessControlInfo
     */
    'ActiveOptionIdx'?: number;
    /**
     * List of remarks arisen during the procedure.
     * @type {Array<ParsingNotificationCodes>}
     * @memberof RfidAccessControlInfo
     */
    'Notifications': Array<ParsingNotificationCodes>;
    /**
     * List of structures with are used to describe the variants of the authentication or secure data access procedure performance within the context of the communication session with electronic document
     * @type {Array<any>}
     * @memberof RfidAccessControlInfo
     */
    'AccessControlOptions'?: Array<any>;
}



