/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TrfFtString } from './trf-ft-string';

/**
 * Structure contains information on a certificate validity.
 * @export
 * @interface RfidValidity
 */
export interface RfidValidity {
    /**
     * 
     * @type {TrfFtString}
     * @memberof RfidValidity
     */
    'NotBefore': TrfFtString;
    /**
     * 
     * @type {TrfFtString}
     * @memberof RfidValidity
     */
    'NotAfter': TrfFtString;
}

