/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Enumeration contains a set of constants specifying the rate of data exchange between the reader and the RFID-chip
 * @export
 * @enum {string}
 */
export enum RfidBaudRate {
    /**
    * Unknown
    */
    UNKNOWN = 0,
    /**
    * 106 bits/s
    */
    RFBR_106 = 1,
    /**
    * 212 bits/s
    */
    RFBR_212 = 2,
    /**
    * 424 bits/s
    */
    RFBR_424 = 4,
    /**
    * 848 bits/s
    */
    RFBR_848 = 8
}



