/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @enum {number}
 */

export enum RfidAccessControl {
    /**
    * Default
    */
    DEFAULT = 0,
    /**
    * Chip access BAC
    */
    CHIP_ACCESS_BAC = 1,
    /**
    * Chip access PACE
    */
    CHIP_ACCESS_PACE = 2,
    /**
    * Local PIN
    */
    LOCAL_PIN = 3
}



