/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * Enumeration contains a set of constants that define the type of certificate used in the procedure of document security object digital signature verification
 * @export
 * @enum {number}
 */

export enum RfidCertificateType {
    /**
    * Type is not defined
    */
    UNDEFINED = 0,
    /**
    * CSCA
    */
    CSCA = 1,
    /**
    * CSCA-link
    */
    CSCA_LINK = 2,
    /**
    * DS
    */
    DS = 3,
    /**
    * Master List signer
    */
    MLS = 4,
    /**
    * Deviaton List signer
    */
    DEV_LS = 5,
    /**
    * Defect List signer
    */
    DEF_LS = 6,
    /**
    * Black List signer
    */
    BLS = 7,
    /**
    * LDS 2
    */
    LDS2 = 8,
    /**
    * Barcode signer (VDS)
    */
    BCS = 9,
    /**
    * Barcode signer (VDS for non-constrained environment)
    */
    BCS_NC = 10,
    /**
    * DTC signer
    */
    DTCS = 11
}



