/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 8.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Enumeration representing RFID Data Group Types. Constants with prefix  correspond to the informational data groups of ePassport application, with prefix EID_ – those of eID application, with prefix EDL_ – eDL application
 * @export
 * @enum {number}
 */

export enum RfidDataGroupTypeTag {
    /**
    * Common Data Element
    */
    COM = 96,
    /**
    * Data Group 1
    */
    DG1 = 97,
    /**
    * Data Group 2
    */
    DG2 = 117,
    /**
    * Data Group 3
    */
    DG3 = 99,
    /**
    * Data Group 4
    */
    DG4 = 118,
    /**
    * Data Group 5
    */
    DG5 = 101,
    /**
    * Data Group 6
    */
    DG6 = 102,
    /**
    * Data Group 7
    */
    DG7 = 103,
    /**
    * Data Group 8
    */
    DG8 = 104,
    /**
    * Data Group 9
    */
    DG9 = 105,
    /**
    * Data Group 10
    */
    DG10 = 106,
    /**
    * Data Group 11
    */
    DG11 = 107,
    /**
    * Data Group 12
    */
    DG12 = 108,
    /**
    * Data Group 13
    */
    DG13 = 109,
    /**
    * Data Group 14
    */
    DG14 = 110,
    /**
    * Data Group 15
    */
    DG15 = 111,
    /**
    * Data Group 16
    */
    DG16 = 112,
    /**
    * Security Object Document
    */
    SOD = 119,
    /**
    * Data Group 17
    */
    DG17 = 113,
    /**
    * Data Group 18
    */
    DG18 = 114,
    /**
    * Data Group 22
    */
    DG22 = 115,
    /**
    * Data Group 23
    */
    DG23 = 116,
    /**
    * Data Group 24
    */
    DG24 = 98,
    /**
    * eID, Data Group 1
    */
    EID_DG1 = 97,
    /**
    * eID, Data Group 2
    */
    EID_DG2 = 98,
    /**
    * eID, Data Group 3
    */
    EID_DG3 = 99,
    /**
    * eID, Data Group 4
    */
    EID_DG4 = 100,
    /**
    * eID, Data Group 5
    */
    EID_DG5 = 101,
    /**
    * eID, Data Group 6
    */
    EID_DG6 = 102,
    /**
    * eID, Data Group 7
    */
    EID_DG7 = 103,
    /**
    * eID, Data Group 8
    */
    EID_DG8 = 104,
    /**
    * eID, Data Group 9
    */
    EID_DG9 = 105,
    /**
    * eID, Data Group 10
    */
    EID_DG10 = 106,
    /**
    * eID, Data Group 11
    */
    EID_DG11 = 107,
    /**
    * eID, Data Group 12
    */
    EID_DG12 = 108,
    /**
    * eID, Data Group 13
    */
    EID_DG13 = 109,
    /**
    * eID, Data Group 14
    */
    EID_DG14 = 110,
    /**
    * eID, Data Group 15
    */
    EID_DG15 = 111,
    /**
    * eID, Data Group 16
    */
    EID_DG16 = 112,
    /**
    * eID, Data Group 17
    */
    EID_DG17 = 113,
    /**
    * eID, Data Group 18
    */
    EID_DG18 = 114,
    /**
    * eID, Data Group 19
    */
    EID_DG19 = 115,
    /**
    * eID, Data Group 20
    */
    EID_DG20 = 116,
    /**
    * eID, Data Group 21
    */
    EID_DG21 = 117,
    /**
    * eDL, Common Data Element
    */
    EDL_COM = 96,
    /**
    * eDL, Security Object Document
    */
    EDL_SOD = 119,
    /**
    * eDL, Card Entitlement
    */
    EDL_CE = 83,
    /**
    * eDL, Data Group 1
    */
    EDL_DG1 = 97,
    /**
    * eDL, Data Group 2
    */
    EDL_DG2 = 107,
    /**
    * eDL, Data Group 3
    */
    EDL_DG3 = 108,
    /**
    * eDL, Data Group 4
    */
    EDL_DG4 = 101,
    /**
    * eDL, Data Group 5
    */
    EDL_DG5 = 103,
    /**
    * eDL, Data Group 6
    */
    EDL_DG6 = 117,
    /**
    * eDL, Data Group 7
    */
    EDL_DG7 = 99,
    /**
    * eDL, Data Group 8
    */
    EDL_DG8 = 118,
    /**
    * eDL, Data Group 9
    */
    EDL_DG9 = 112,
    /**
    * eDL, Data Group 11
    */
    EDL_DG11 = 109,
    /**
    * eDL, Data Group 12
    */
    EDL_DG12 = 113,
    /**
    * eDL, Data Group 13
    */
    EDL_DG13 = 111,
    /**
    * eDL, Data Group 14
    */
    EDL_DG14 = 110
}



