/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Enumeration contains a set of constants that define the type of performed procedure of document authentication within the current session
 * @export
 * @enum {number}
 */

export enum RfidAuthenticationProcedureType {
    /**
    * Not defined
    */
    UNDEFINED = 0,
    /**
    * Standard authentication procedure
    */
    STANDARD = 1,
    /**
    * Advanced authentication procedure
    */
    ADVANCED = 2,
    /**
    * General authentication procedure
    */
    GENERAL = 3
}



