/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TrfFtString } from './trf-ft-string';

/**
 * Structure contains information that serves as the distinguished name (identifier) of an object.
 * @export
 * @interface RfidAttributeName
 */
export interface RfidAttributeName {
    /**
     * Attribute identifier (OID ASCII string); contents of the identifier in the format S1 (S2), where S1 – attribute name, S2 – identifier (OID string)
     * @type {string}
     * @memberof RfidAttributeName
     */
    'Type': string;
    /**
     * 
     * @type {TrfFtString}
     * @memberof RfidAttributeName
     */
    'Value': TrfFtString;
}

