/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LCID } from './lcid';
// May contain unused imports in some cases
// @ts-ignore
import type { RFIDDocVisualExtendedFieldItem } from './rfiddoc-visual-extended-field-item';
// May contain unused imports in some cases
// @ts-ignore
import type { StringRecognitionResult } from './string-recognition-result';
// May contain unused imports in some cases
// @ts-ignore
import type { TextFieldType } from './text-field-type';
// May contain unused imports in some cases
// @ts-ignore
import type { VisualExtendedFieldItem } from './visual-extended-field-item';

/**
 * @type RFIDDocVisualExtendedField
 * @export
 */
export type RFIDDocVisualExtendedField = RFIDDocVisualExtendedFieldItem & VisualExtendedFieldItem;


