/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ParsingNotificationCodes } from './parsing-notification-codes';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidSignerInfoEx } from './rfid-signer-info-ex';

/**
 * Structure is used to describe the contents of a single document security object (SO) and the results of its check within the context of the communication session with electronic document
 * @export
 * @interface RfidSecurityObject
 */
export interface RfidSecurityObject {
    /**
     * Security object version
     * @type {number}
     * @memberof RfidSecurityObject
     */
    'Version': number;
    /**
     * Identifier of the security object
     * @type {string}
     * @memberof RfidSecurityObject
     */
    'ObjectType': string;
    /**
     * Reference to the source file of the security object data
     * @type {number}
     * @memberof RfidSecurityObject
     */
    'FileReference': number;
    /**
     * List of remarks arisen during the analysis of SO data structure.
     * @type {Array<ParsingNotificationCodes>}
     * @memberof RfidSecurityObject
     */
    'Notifications': Array<ParsingNotificationCodes>;
    /**
     * List of containers to store information about digital signature objects contained in the SO
     * @type {Array<RfidSignerInfoEx>}
     * @memberof RfidSecurityObject
     */
    'SignerInfos': Array<RfidSignerInfoEx>;
}

