/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Enumeration contains a set of constants specifying the type of the RFID-chip by the physical parameters of connection between antennas of the chip and the reader
 * @export
 * @enum {number}
 */

export enum RfidType {
    /**
    * Unknown
    */
    UNKNOWN = 0,
    /**
    * Type A
    */
    A = 1,
    /**
    * Type B
    */
    B = 2
}



