/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @interface RfidRawData
 */
export interface RfidRawData {
    /**
     * 
     * @type {string}
     * @memberof RfidRawData
     */
    'Data': string;
    /**
     * 
     * @type {number}
     * @memberof RfidRawData
     */
    'FieldType': number;
}

