/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ParsingErrorCodes } from './parsing-error-codes';
// May contain unused imports in some cases
// @ts-ignore
import type { RFIDErrorCodes } from './rfiderror-codes';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidCertificateOrigin } from './rfid-certificate-origin';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidCertificateType } from './rfid-certificate-type';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidDistinguishedName } from './rfid-distinguished-name';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidPkiExtension } from './rfid-pki-extension';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidValidity } from './rfid-validity';
// May contain unused imports in some cases
// @ts-ignore
import type { TrfFtString } from './trf-ft-string';

/**
 * Structure is used to describe the certificate contents used for the digital signature verification of the document security object within the context of the communication session with electronic document.
 * @export
 * @interface RfidCertificateEx
 */
export interface RfidCertificateEx {
    /**
     * Version of Certificate ASN.1 structure
     * @type {number}
     * @memberof RfidCertificateEx
     */
    'Version': number;
    /**
     * Certificate serial number. Base64 encoded.
     * @type {string}
     * @memberof RfidCertificateEx
     */
    'SerialNumber': string;
    /**
     * Certificate digital signature algorithm identifier (OID); String in the format S1 (S2), where S1 – algorithm name, S2 – identifier (OID string).
     * @type {string}
     * @memberof RfidCertificateEx
     */
    'SignatureAlgorithm': string;
    /**
     * 
     * @type {RfidDistinguishedName}
     * @memberof RfidCertificateEx
     */
    'Issuer': RfidDistinguishedName;
    /**
     * 
     * @type {RfidValidity}
     * @memberof RfidCertificateEx
     */
    'Validity': RfidValidity;
    /**
     * 
     * @type {RfidDistinguishedName}
     * @memberof RfidCertificateEx
     */
    'Subject': RfidDistinguishedName;
    /**
     * Certificate public key algorithm identifier (OID); String in the format S1 (S2), where S1 – algorithm name, S2 – identifier (OID string).
     * @type {string}
     * @memberof RfidCertificateEx
     */
    'SubjectPKAlgorithm': string;
    /**
     * List of the certificate extensions
     * @type {Array<RfidPkiExtension>}
     * @memberof RfidCertificateEx
     */
    'Extensions': Array<RfidPkiExtension>;
    /**
     * List of remarks arisen during the analysis of the certificate data structure and its validity verification.
     * @type {Array<ParsingErrorCodes>}
     * @memberof RfidCertificateEx
     */
    'Notifications': Array<ParsingErrorCodes>;
    /**
     * 
     * @type {RfidCertificateOrigin}
     * @memberof RfidCertificateEx
     */
    'Origin': RfidCertificateOrigin;
    /**
     * 
     * @type {RfidCertificateType}
     * @memberof RfidCertificateEx
     */
    'Type': RfidCertificateType;
    /**
     * 
     * @type {TrfFtString}
     * @memberof RfidCertificateEx
     */
    'FileName': TrfFtString;
    /**
     * 
     * @type {RFIDErrorCodes}
     * @memberof RfidCertificateEx
     */
    'PA_Status': RFIDErrorCodes;
}



