/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * Enumeration contains a set of constants specifying the rate of data exchange between the reader and the RFID-chip
 * @export
 * @enum {number}
 */

export enum RfidPasswordType {
    /**
    * Unknown type
    */
    UNKNOWN = 0,
    /**
    * MRZ
    */
    MRZ = 1,
    /**
    * CAN
    */
    CAN = 2,
    /**
    * PIN
    */
    PIN = 3,
    /**
    * PUK
    */
    PUK = 4,
    /**
    * eSign-PIN
    */
    PIN_E_SIGN = 5,
    /**
    * Scanning Area Identifier (for eDL application)
    */
    SAI = 6,
    /**
    * MRZ hash
    */
    MRZ_HASH = 7
}



