/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RfidAttributeName } from './rfid-attribute-name';
// May contain unused imports in some cases
// @ts-ignore
import type { TrfFtString } from './trf-ft-string';

/**
 * Contents of the identifier in binary form. Base64 encoded.
 * @export
 * @interface RfidDistinguishedName
 */
export interface RfidDistinguishedName {
    /**
     * Contents of the identifier in binary form. Base64 encoded.
     * @type {string}
     * @memberof RfidDistinguishedName
     */
    'Data': string;
    /**
     * 
     * @type {TrfFtString}
     * @memberof RfidDistinguishedName
     */
    'FriendlyName': TrfFtString;
    /**
     * List of individual attributes contained in the identifier
     * @type {Array<RfidAttributeName>}
     * @memberof RfidDistinguishedName
     */
    'Attributes': Array<RfidAttributeName>;
}

