/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Enumeration contains a set of constants that define the type of certificate
 * @export
 * @enum {number}
 */

export enum RFIDPKDResourceType {
    /**
    * Certificate file contents (.pem, .cer, .crt, .der)
    */
    CERTIFICATE_PA = 0,
    /**
    * Certificate file contents (.cvcert) and private key file contents (.pkcs8)
    */
    CERTIFICATE_TA = 1,
    /**
    * LDIF file contents (.ldif)
    */
    LDIF = 2,
    /**
    * CRL file contents (.crl)
    */
    CRL = 3,
    /**
    * Master List (.ml, .mls)
    */
    ML = 4,
    /**
    * Defect List (.dl, .dls, .dfl)
    */
    DEFL = 5,
    /**
    * Deviance List (.dl, .dls, .dvl)
    */
    DEVL = 6,
    /**
    * Black List (.bl, .bls)
    */
    BL = 7
}



