/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CheckResult } from './check-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RFIDErrorCodes } from './rfiderror-codes';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidAccessControlInfo } from './rfid-access-control-info';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidAccessKey } from './rfid-access-key';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidApplication } from './rfid-application';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidAuthenticationProcedureType } from './rfid-authentication-procedure-type';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidCardPropertiesExt } from './rfid-card-properties-ext';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidSecurityObject } from './rfid-security-object';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidTerminal } from './rfid-terminal';

/**
 * Structure is used to describe the results of work with the SDK within the context of the current communication session with electronic document
 * @export
 * @interface RfidSessionData
 */
export interface RfidSessionData {
    /**
     * Sign of virtual session when working with loaded data from a previous communication session with the electronic document
     * @type {string}
     * @memberof RfidSessionData
     */
    'VirtualMode'?: string;
    /**
     * Text SDKVersion value in format A.B (e.g. 3.1)
     * @type {string}
     * @memberof RfidSessionData
     */
    'SDKVersion'?: string;
    /**
     * Text DriverVersion value in format A.B.C.D (e.g. 6.2.5.4)
     * @type {string}
     * @memberof RfidSessionData
     */
    'DriverVersion'?: string;
    /**
     * Text FirmwareVersion value in format A.B (e.g. 5.19)
     * @type {string}
     * @memberof RfidSessionData
     */
    'FirmwareVersion'?: string;
    /**
     * List of containers to store information about the involved applications of electronic document
     * @type {Array<RfidApplication>}
     * @memberof RfidSessionData
     */
    'Applications': Array<RfidApplication>;
    /**
     * List of containers to store information about the supported procedures of authentication and secure data access within the context of the session
     * @type {Array<RfidAccessControlInfo>}
     * @memberof RfidSessionData
     */
    'AccessControls': Array<RfidAccessControlInfo>;
    /**
     * 
     * @type {RfidCardPropertiesExt}
     * @memberof RfidSessionData
     */
    'CardProperties': RfidCardPropertiesExt;
    /**
     * 
     * @type {RFIDErrorCodes}
     * @memberof RfidSessionData
     */
    'ExtLeSupport': RFIDErrorCodes;
    /**
     * Time of processing, milliseconds
     * @type {number}
     * @memberof RfidSessionData
     */
    'ProcessTime': number;
    /**
     * List of containers to store information about the read files of the root Master File
     * @type {Array<any>}
     * @memberof RfidSessionData
     */
    'RootFiles': Array<any>;
    /**
     * Total number of bytes transmitted to the RFID-chip during the whole session
     * @type {number}
     * @memberof RfidSessionData
     */
    'TotalBytesSent': number;
    /**
     * Total number of bytes received from the RFID-chip during the whole session
     * @type {number}
     * @memberof RfidSessionData
     */
    'TotalBytesReceived': number;
    /**
     * 
     * @type {RfidAccessKey}
     * @memberof RfidSessionData
     */
    'Session_key': RfidAccessKey;
    /**
     * 
     * @type {RfidTerminal}
     * @memberof RfidSessionData
     */
    'Session_terminal': RfidTerminal;
    /**
     * 
     * @type {RfidAuthenticationProcedureType}
     * @memberof RfidSessionData
     */
    'Session_procedure': RfidAuthenticationProcedureType;
    /**
     * List of containers to store information about the detected document security objects
     * @type {Array<RfidSecurityObject>}
     * @memberof RfidSessionData
     */
    'SecurityObjects': Array<RfidSecurityObject>;
    /**
     * 
     * @type {CheckResult}
     * @memberof RfidSessionData
     */
    'Status'?: CheckResult;
}



