/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CertificateData } from './certificate-data';

/**
 * 
 * @export
 * @interface SecurityObjectCertificates
 */
export interface SecurityObjectCertificates {
    /**
     * 
     * @type {CertificateData}
     * @memberof SecurityObjectCertificates
     */
    'Certificate_Data'?: CertificateData;
}

