/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */



/**
 * Document data sources
 * @export
 * @enum {string}
 */

export enum Source {
    /**
    * Machine readable zone (MRZ)
    */
    MRZ = 'MRZ',
    /**
    * Visual zone
    */
    VISUAL = 'VISUAL',
    /**
    * Barcode
    */
    BARCODE = 'BARCODE',
    /**
    * RFID
    */
    RFID = 'RFID',
    /**
    * Magnetic
    */
    MAGNETIC = 'MAGNETIC',
    /**
    * External
    */
    EXTERNAL = 'EXTERNAL'
}



