/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Status } from './status';

/**
 * 
 * @export
 * @interface StatusItem
 */
export interface StatusItem {
    /**
     * 
     * @type {Status}
     * @memberof StatusItem
     */
    'Status': Status;
}

