/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CheckResult } from './check-result';
// May contain unused imports in some cases
// @ts-ignore
import type { DetailsAge } from './details-age';
// May contain unused imports in some cases
// @ts-ignore
import type { DetailsOptical } from './details-optical';
// May contain unused imports in some cases
// @ts-ignore
import type { DetailsRFID } from './details-rfid';

/**
 * 
 * @export
 * @interface Status
 */
export interface Status {
    /**
     * Overall checks status. Rootx status
     * @type {CheckResult}
     * @memberof Status
     */
    'overallStatus': CheckResult;
    /**
     * Overall optical checks combined status
     * @type {CheckResult}
     * @memberof Status
     */
    'optical': CheckResult;
    /**
     * Portrait comparison status
     * @type {CheckResult}
     * @memberof Status
     */
    'portrait': CheckResult;
    /**
     * Overall RFID checks combined status
     * @type {CheckResult}
     * @memberof Status
     */
    'rfid': CheckResult;
    /**
     * Stop list check status
     * @type {CheckResult}
     * @memberof Status
     */
    'stopList': CheckResult;
    /**
     * 
     * @type {DetailsRFID}
     * @memberof Status
     */
    'detailsRFID'?: DetailsRFID;
    /**
     * 
     * @type {DetailsOptical}
     * @memberof Status
     */
    'detailsOptical': DetailsOptical;
    /**
     * 
     * @type {CheckResult}
     * @memberof Status
     */
    'age': CheckResult;
    /**
     * 
     * @type {DetailsAge}
     * @memberof Status
     */
    'detailsAge': DetailsAge;
    /**
     * 
     * @type {CheckResult}
     * @memberof Status
     */
    'mDL': CheckResult;
}



