/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @interface Symbol
 */
export interface Symbol {
    /**
     * 
     * @type {Array<number>}
     * @memberof Symbol
     */
    'boundingRect': Array<number>;
}

