/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RectangleCoordinates } from './rectangle-coordinates';

/**
 * 
 * @export
 * @interface SymbolEstimationItem
 */
export interface SymbolEstimationItem {
    /**
     * 
     * @type {number}
     * @memberof SymbolEstimationItem
     */
    'ALIGNMENT_NEAREST_SYMBOLS': number;
    /**
     * 
     * @type {number}
     * @memberof SymbolEstimationItem
     */
    'CONTRAST_PRINT': number;
    /**
     * 
     * @type {number}
     * @memberof SymbolEstimationItem
     */
    'CONTRAST_SYMBOL': number;
    /**
     * 
     * @type {number}
     * @memberof SymbolEstimationItem
     */
    'CharSymbol': number;
    /**
     * 
     * @type {number}
     * @memberof SymbolEstimationItem
     */
    'EDGE': number;
    /**
     * 
     * @type {number}
     * @memberof SymbolEstimationItem
     */
    'EMPTINESS': number;
    /**
     * 
     * @type {number}
     * @memberof SymbolEstimationItem
     */
    'STAIN': number;
    /**
     * 
     * @type {number}
     * @memberof SymbolEstimationItem
     */
    'SYMBOLS_INTERVAL': number;
    /**
     * 
     * @type {number}
     * @memberof SymbolEstimationItem
     */
    'SYMBOL_PARAM': number;
    /**
     * 
     * @type {number}
     * @memberof SymbolEstimationItem
     */
    'SYMBOL_SIZE': number;
    /**
     * 
     * @type {number}
     * @memberof SymbolEstimationItem
     */
    'SizeErrorAlignWithNext': number;
    /**
     * 
     * @type {number}
     * @memberof SymbolEstimationItem
     */
    'SizeErrorAlignWithPrev': number;
    /**
     * 
     * @type {number}
     * @memberof SymbolEstimationItem
     */
    'SizeErrorIntervWithNext': number;
    /**
     * 
     * @type {number}
     * @memberof SymbolEstimationItem
     */
    'SizeErrorIntervWithPrev': number;
    /**
     * 
     * @type {number}
     * @memberof SymbolEstimationItem
     */
    'SizeErrorSymbolHeight': number;
    /**
     * 
     * @type {number}
     * @memberof SymbolEstimationItem
     */
    'SizeErrorSymbolWidth': number;
    /**
     * 
     * @type {RectangleCoordinates}
     * @memberof SymbolEstimationItem
     */
    'SymbolBounds': RectangleCoordinates;
}

