/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Describes an individual character recognition candidate
 * @export
 * @interface SymbolCandidate
 */
export interface SymbolCandidate {
    /**
     * Unicode symbol code
     * @type {number}
     * @memberof SymbolCandidate
     */
    'SymbolCode': number;
    /**
     * character recognition probability (0–100,%)
     * @type {number}
     * @memberof SymbolCandidate
     */
    'SymbolProbability': number;
    /**
     * 
     * @type {number}
     * @memberof SymbolCandidate
     */
    'Class'?: number;
    /**
     * 
     * @type {number}
     * @memberof SymbolCandidate
     */
    'SubClass'?: number;
}

