/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BinaryData } from './binary-data';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidRawData } from './rfid-raw-data';

/**
 * 
 * @export
 * @interface TDocBinaryInfo
 */
export interface TDocBinaryInfo {
    /**
     * 
     * @type {BinaryData}
     * @memberof TDocBinaryInfo
     */
    'RFID_BINARY_DATA'?: BinaryData;
    /**
     * 
     * @type {Array<RfidRawData>}
     * @memberof TDocBinaryInfo
     */
    'RFID_RAW_DATA'?: Array<RfidRawData>;
}

