/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TDocBinaryInfo } from './tdoc-binary-info';

/**
 * 
 * @export
 * @interface TDocBinaryInfoItem
 */
export interface TDocBinaryInfoItem {
    /**
     * 
     * @type {TDocBinaryInfo}
     * @memberof TDocBinaryInfoItem
     */
    'TDocBinaryInfo': TDocBinaryInfo;
}

