/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Text } from './text';

/**
 * 
 * @export
 * @interface TextItem
 */
export interface TextItem {
    /**
     * 
     * @type {Text}
     * @memberof TextItem
     */
    'Text': Text;
}

