/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CheckResult } from './check-result';
// May contain unused imports in some cases
// @ts-ignore
import type { TextAvailableSource } from './text-available-source';
// May contain unused imports in some cases
// @ts-ignore
import type { TextField } from './text-field';

/**
 * Contains all document text fields data with validity and cross-source compare checks
 * @export
 * @interface Text
 */
export interface Text {
    /**
     * Overall status of all checks from all text fields
     * @type {CheckResult}
     * @memberof Text
     */
    'status': CheckResult;
    /**
     * Overall status of validity from all text fields from all sources
     * @type {CheckResult}
     * @memberof Text
     */
    'validityStatus': CheckResult;
    /**
     * Overall status of data comparison from different sources for each text field
     * @type {CheckResult}
     * @memberof Text
     */
    'comparisonStatus': CheckResult;
    /**
     * Date format
     * @type {string}
     * @memberof Text
     */
    'dateFormat': string;
    /**
     * 
     * @type {Array<TextField>}
     * @memberof Text
     */
    'fieldList': Array<TextField>;
    /**
     * 
     * @type {Array<TextAvailableSource>}
     * @memberof Text
     */
    'availableSourceList': Array<TextAvailableSource>;
}



