/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CheckResult } from './check-result';
// May contain unused imports in some cases
// @ts-ignore
import type { Source } from './source';

/**
 * 
 * @export
 * @interface TextAvailableSource
 */
export interface TextAvailableSource {
    /**
     * 
     * @type {Source}
     * @memberof TextAvailableSource
     */
    'source': Source;
    /**
     * 
     * @type {CheckResult}
     * @memberof TextAvailableSource
     */
    'validityStatus': CheckResult;
    /**
     * Same as Result type, but used for safe parsing of not-described values. See Result type.
     * @type {number}
     * @memberof TextAvailableSource
     */
    'containerType'?: number;
}



