/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @enum {number}
 */

export enum TextPostProcessing {
    /**
    * Do not change
    */
    NO_CHANGE = 0,
    /**
    * Uppercase
    */
    UPPERCASE = 1,
    /**
    * Lowercase
    */
    LOWERCASE = 2,
    /**
    * Capital
    */
    CAPITAL = 3
}



