/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.  # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TOriginalRFIDGraphics
 */
export interface TOriginalRFIDGraphics {
    /**
     * 
     * @type {number}
     * @memberof TOriginalRFIDGraphics
     */
    FieldType?: number;
    /**
     * 
     * @type {number}
     * @memberof TOriginalRFIDGraphics
     */
    GraphicsType?: number;
    /**
     * 
     * @type {number}
     * @memberof TOriginalRFIDGraphics
     */
    RFID_OriginDG?: number;
    /**
     * 
     * @type {number}
     * @memberof TOriginalRFIDGraphics
     */
    RFID_OriginDGTag?: number;
    /**
     * 
     * @type {number}
     * @memberof TOriginalRFIDGraphics
     */
    RFID_OriginTagEntry?: number;
    /**
     * 
     * @type {number}
     * @memberof TOriginalRFIDGraphics
     */
    RFID_OriginEntryView?: number;
    /**
     * 
     * @type {number}
     * @memberof TOriginalRFIDGraphics
     */
    Buf_Length?: number;
    /**
     * 
     * @type {string}
     * @memberof TOriginalRFIDGraphics
     */
    Buffer?: string;
}


