/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TOriginalRFIDGraphicsInfo } from './toriginal-rfidgraphics-info';

/**
 * 
 * @export
 * @interface TOriginalRFIDGraphicsInfoItem
 */
export interface TOriginalRFIDGraphicsInfoItem {
    /**
     * 
     * @type {TOriginalRFIDGraphicsInfo}
     * @memberof TOriginalRFIDGraphicsInfoItem
     */
    'TOriginalRFIDGraphicsInfo': TOriginalRFIDGraphicsInfo;
}

