/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GraphData } from './graph-data';

/**
 * 
 * @export
 * @interface TOriginalRFIDGraphicsInfo
 */
export interface TOriginalRFIDGraphicsInfo {
    /**
     * 
     * @type {Array<GraphData>}
     * @memberof TOriginalRFIDGraphicsInfo
     */
    'RFID_ORIGINAL_GRAPH_DATA': Array<GraphData>;
}

