/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DocumentsDatabase } from './documents-database';

/**
 * 
 * @export
 * @interface TransactionInfo
 */
export interface TransactionInfo {
    /**
     * Computer name
     * @type {string}
     * @memberof TransactionInfo
     */
    'ComputerName'?: string;
    /**
     * Date and time
     * @type {string}
     * @memberof TransactionInfo
     */
    'DateTime'?: string;
    /**
     * 
     * @type {DocumentsDatabase}
     * @memberof TransactionInfo
     */
    'DocumentsDatabase'?: DocumentsDatabase;
    /**
     * System information
     * @type {string}
     * @memberof TransactionInfo
     */
    'SystemInfo'?: string;
    /**
     * Transaction tag
     * @type {string}
     * @memberof TransactionInfo
     */
    'Tag'?: string;
    /**
     * Transaction identifier
     * @type {string}
     * @memberof TransactionInfo
     */
    'TransactionID'?: string;
    /**
     * User name
     * @type {string}
     * @memberof TransactionInfo
     */
    'UserName'?: string;
    /**
     * SDK version
     * @type {string}
     * @memberof TransactionInfo
     */
    'Version'?: string;
}

