/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ImagesFieldValue } from './images-field-value';

/**
 * 
 * @export
 * @interface TransactionImage
 */
export interface TransactionImage {
    /**
     * 
     * @type {ImagesFieldValue}
     * @memberof TransactionImage
     */
    'image'?: ImagesFieldValue;
}

