/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContainerList } from './container-list';
// May contain unused imports in some cases
// @ts-ignore
import type { ProcessingStatus } from './processing-status';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidLocation } from './rfid-location';
// May contain unused imports in some cases
// @ts-ignore
import type { TransactionInfo } from './transaction-info';

/**
 * 
 * @export
 * @interface TransactionProcessResponse
 */
export interface TransactionProcessResponse {
    /**
     * 
     * @type {number}
     * @memberof TransactionProcessResponse
     */
    'CoreLibResultCode': number;
    /**
     * 
     * @type {RfidLocation}
     * @memberof TransactionProcessResponse
     */
    'ChipPage': RfidLocation;
    /**
     * 
     * @type {ProcessingStatus}
     * @memberof TransactionProcessResponse
     */
    'ProcessingFinished': ProcessingStatus;
    /**
     * 
     * @type {ContainerList}
     * @memberof TransactionProcessResponse
     */
    'ContainerList': ContainerList;
    /**
     * 
     * @type {TransactionInfo}
     * @memberof TransactionProcessResponse
     */
    'TransactionInfo': TransactionInfo;
    /**
     * Base64 encoded transaction processing log
     * @type {string}
     * @memberof TransactionProcessResponse
     */
    'log'?: string;
    /**
     * Free-form object provided in request. See passBackObject property of ProcessRequest.
     * @type {{ [key: string]: any; }}
     * @memberof TransactionProcessResponse
     */
    'passBackObject'?: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof TransactionProcessResponse
     */
    'morePagesAvailable': number;
    /**
     * Time the document processing has taken, ms.
     * @type {number}
     * @memberof TransactionProcessResponse
     */
    'elapsedTime': number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof TransactionProcessResponse
     */
    'metadata'?: { [key: string]: any; };
}



