/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InData } from './in-data';
// May contain unused imports in some cases
// @ts-ignore
import type { OutData } from './out-data';

/**
 * 
 * @export
 * @interface TransactionProcessGetResponse
 */
export interface TransactionProcessGetResponse {
    /**
     * 
     * @type {string}
     * @memberof TransactionProcessGetResponse
     */
    'transactionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionProcessGetResponse
     */
    'tag'?: string;
    /**
     * 
     * @type {OutData}
     * @memberof TransactionProcessGetResponse
     */
    'outData'?: OutData;
    /**
     * 
     * @type {InData}
     * @memberof TransactionProcessGetResponse
     */
    'inData'?: InData;
}

