/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Structure is used to store an array of binary information that is a part of one of the informational data groups
 * @export
 * @interface TrfFtBytes
 */
export interface TrfFtBytes {
    /**
     * Logical type of the field
     * @type {number}
     * @memberof TrfFtBytes
     */
    'Type': number;
    /**
     * Result of logical analysis of compliance of the contents of the field with the requirements of the specification
     * @type {number}
     * @memberof TrfFtBytes
     */
    'Status': number;
    /**
     * Length of Data array
     * @type {number}
     * @memberof TrfFtBytes
     */
    'Length': number;
    /**
     * Binary data array. Base64 encoded.
     * @type {string}
     * @memberof TrfFtBytes
     */
    'Data': string | null;
}

