/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Structure is used to store information about the numeric field (4 bytes) that is a part of one of the informational data groups.
 * @export
 * @interface TrfFtString
 */
export interface TrfFtString {
    /**
     * 
     * @type {number}
     * @memberof TrfFtString
     */
    'Type'?: number;
    /**
     * Result of logical analysis of compliance of the contents of the field with the requirements of the specification
     * @type {number}
     * @memberof TrfFtString
     */
    'Status'?: number;
    /**
     * Mask of format of text information (for example, «YYMMDD» for date of birth)
     * @type {string}
     * @memberof TrfFtString
     */
    'Format'?: string;
    /**
     * Numeric value.
     * @type {string}
     * @memberof TrfFtString
     */
    'Data': string;
}

