/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * 
 * @export
 * @interface VDItem
 */
export interface VDItem {
    /**
     * 
     * @type {string}
     * @memberof VDItem
     */
    'adm'?: string;
    /**
     * 
     * @type {string}
     * @memberof VDItem
     */
    'ctr'?: string;
    /**
     * 
     * @type {string}
     * @memberof VDItem
     */
    'dvc'?: string;
    /**
     * 
     * @type {string}
     * @memberof VDItem
     */
    'lot'?: string;
    /**
     * 
     * @type {number}
     * @memberof VDItem
     */
    'seq'?: number;
}

