/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { VDSData } from './vdsdata';

/**
 * 
 * @export
 * @interface VDSDataItem
 */
export interface VDSDataItem {
    /**
     * 
     * @type {VDSData}
     * @memberof VDSDataItem
     */
    'dftVDS': VDSData;
}

