/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DocFeature } from './doc-feature';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidCertificateEx } from './rfid-certificate-ex';
// May contain unused imports in some cases
// @ts-ignore
import type { TrfFtBytes } from './trf-ft-bytes';

/**
 * 
 * @export
 * @interface VDSData
 */
export interface VDSData {
    /**
     * 
     * @type {string}
     * @memberof VDSData
     */
    'Certificate'?: string;
    /**
     * 
     * @type {Array<RfidCertificateEx>}
     * @memberof VDSData
     */
    'CertificateChain'?: Array<RfidCertificateEx>;
    /**
     * 
     * @type {Array<DocFeature>}
     * @memberof VDSData
     */
    'DocFeatures'?: Array<DocFeature>;
    /**
     * 
     * @type {string}
     * @memberof VDSData
     */
    'DocIssueDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof VDSData
     */
    'DocType'?: number;
    /**
     * 
     * @type {number}
     * @memberof VDSData
     */
    'FeatureRef'?: number;
    /**
     * 
     * @type {string}
     * @memberof VDSData
     */
    'IssuingCountry'?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof VDSData
     */
    'Notifications'?: Array<number>;
    /**
     * 
     * @type {TrfFtBytes}
     * @memberof VDSData
     */
    'Signature'?: TrfFtBytes;
    /**
     * 
     * @type {string}
     * @memberof VDSData
     */
    'SignatureDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof VDSData
     */
    'Signer'?: string;
    /**
     * 
     * @type {number}
     * @memberof VDSData
     */
    'Type'?: number;
    /**
     * 
     * @type {number}
     * @memberof VDSData
     */
    'Version'?: number;
}

