/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Message } from './message';
// May contain unused imports in some cases
// @ts-ignore
import type { RfidCertificateEx } from './rfid-certificate-ex';
// May contain unused imports in some cases
// @ts-ignore
import type { TrfFtBytes } from './trf-ft-bytes';

/**
 * 
 * @export
 * @interface VDSNCData
 */
export interface VDSNCData {
    /**
     * 
     * @type {TrfFtBytes}
     * @memberof VDSNCData
     */
    'Certificate'?: TrfFtBytes;
    /**
     * 
     * @type {Array<RfidCertificateEx>}
     * @memberof VDSNCData
     */
    'CertificateChain'?: Array<RfidCertificateEx>;
    /**
     * 
     * @type {string}
     * @memberof VDSNCData
     */
    'IssuingCountry'?: string;
    /**
     * 
     * @type {Message}
     * @memberof VDSNCData
     */
    'Message'?: Message;
    /**
     * 
     * @type {Array<number>}
     * @memberof VDSNCData
     */
    'Notifications'?: Array<number>;
    /**
     * 
     * @type {TrfFtBytes}
     * @memberof VDSNCData
     */
    'Signature'?: TrfFtBytes;
    /**
     * 
     * @type {string}
     * @memberof VDSNCData
     */
    'SignatureAlg'?: string;
    /**
     * 
     * @type {string}
     * @memberof VDSNCData
     */
    'Type'?: string;
    /**
     * 
     * @type {number}
     * @memberof VDSNCData
     */
    'Version'?: number;
}

