/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */



/**
 * Enumeration contains visibility status of the security element
 * @export
 * @enum {number}
 */

export enum Visibility {
    /**
    * Invisible
    */
    INVISIBLE = 0,
    /**
    * Visible
    */
    VISIBLE = 1,
    /**
    * Colored
    */
    COLORED = 2,
    /**
    * Grayscale
    */
    GRAYSCALE = 4,
    /**
    * Visible vs IR match
    */
    WHITE_IR_MATCHING = 8
}



