/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do not edit the file manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LCID } from './lcid';
// May contain unused imports in some cases
// @ts-ignore
import type { StringRecognitionResult } from './string-recognition-result';
// May contain unused imports in some cases
// @ts-ignore
import type { TextFieldType } from './text-field-type';

/**
 * 
 * @export
 * @interface VisualExtendedFieldItem
 */
export interface VisualExtendedFieldItem {
    /**
     * 
     * @type {TextFieldType}
     * @memberof VisualExtendedFieldItem
     */
    'wFieldType': TextFieldType;
    /**
     * Field symbolic name (null-terminated string)
     * @type {string}
     * @memberof VisualExtendedFieldItem
     */
    'FieldName': string;
    /**
     * Number of StringsResult array elements
     * @type {number}
     * @memberof VisualExtendedFieldItem
     */
    'StringsCount': number;
    /**
     * Array of recognizing probabilities for a each line of text field. Only for Result.VISUAL_TEXT and Result.MRZ_TEXT results.
     * @type {Array<StringRecognitionResult>}
     * @memberof VisualExtendedFieldItem
     */
    'StringsResult': Array<StringRecognitionResult>;
    /**
     * Buf_Text text string length
     * @type {number}
     * @memberof VisualExtendedFieldItem
     */
    'Buf_Length': number;
    /**
     * Text field data in UTF8 format. Results of reading different lines of a multi-line field are separated by \'^\'
     * @type {string}
     * @memberof VisualExtendedFieldItem
     */
    'Buf_Text': string;
    /**
     * 
     * @type {string}
     * @memberof VisualExtendedFieldItem
     */
    'FieldMask'?: string;
    /**
     * 
     * @type {number}
     * @memberof VisualExtendedFieldItem
     */
    'Validity'?: number;
    /**
     * 
     * @type {number}
     * @memberof VisualExtendedFieldItem
     */
    'InComparison'?: number;
    /**
     * 
     * @type {LCID}
     * @memberof VisualExtendedFieldItem
     */
    'wLCID'?: LCID;
    /**
     * 
     * @type {number}
     * @memberof VisualExtendedFieldItem
     */
    'Reserved2'?: number;
    /**
     * 
     * @type {number}
     * @memberof VisualExtendedFieldItem
     */
    'Reserved3'?: number;
}



