name: run smoke test

on:
  pull_request:
    branches:
      - master
      - develop
      - stable

jobs:
  run_smoke_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build
      - run: npm install && node --unhandled-rejections=strict index.js
        working-directory: ./examples/basic/
        env:
          API_BASE_PATH: "https://nightly-api.regulaforensics.com"
          TEST_LICENSE: ${{secrets.TEST_LICENSE}}
